using System;
using System.Collections.Concurrent;
using System.Collections.Generic;
using System.Runtime.Serialization;
using OpenRiaServices.Server;

#nullable disable

namespace OpenRiaServices.Hosting.Wcf
{
    internal class DomainServiceSerializationSurrogate
#if ASPNET_CORE
        : ISerializationSurrogateProvider
#else
        : IDataContractSurrogate
#endif
    {
        private readonly DomainServiceDescription _description;
        private readonly ConcurrentDictionary<Type, (Type surrogateType, Func<object, object> surrogateFactory)> _exposedTypeToSurrogateMap;
        private readonly HashSet<Type> _surrogateTypes;

        /// <summary>
        /// Default constructor.
        /// </summary>
        /// <param name="description">A description of the <see cref="DomainService"/> this type creates surrogates for.</param>
        public DomainServiceSerializationSurrogate(DomainServiceDescription description)
        {
            this._description = description;
            _surrogateTypes = new HashSet<Type>();
            _exposedTypeToSurrogateMap = new ConcurrentDictionary<Type, (Type, Func<object, object>)>();

            // Cache the list of entity types and surrogate types.
            HashSet<Type> exposedTypes = new HashSet<Type>(description.EntityTypes);

            // Because complex types and entities cannot share an inheritance relationship, we can add them to the same surrogate set.
            exposedTypes.UnionWith(description.ComplexTypes);

            foreach (Type exposedType in exposedTypes)
            {
                Type surrogateType = DataContractSurrogateGenerator.GetSurrogateType(exposedTypes, exposedType);
                Func<object, object> surrogateFactory = (Func<object, object>)DynamicMethodUtility.GetFactoryMethod(surrogateType.GetConstructor([exposedType]), typeof(Func<object, object>));
                _exposedTypeToSurrogateMap.TryAdd(exposedType, (surrogateType, surrogateFactory));
                _surrogateTypes.Add(surrogateType);
            }
        }

        public IReadOnlyCollection<Type> SurrogateTypes => this._surrogateTypes;

#if ASPNET_CORE
        public Type GetSurrogateType(Type type)
#else
        public Type GetDataContractType(Type type)
#endif
        {
            if (this._exposedTypeToSurrogateMap.TryGetValue(type, out var surrogateInfo))
            {
                return surrogateInfo.surrogateType;
            }
            return type;
        }

        public object GetDeserializedObject(object obj, Type targetType)
        {
            if (this._surrogateTypes.Contains(obj.GetType()))
            {
                return ((ICloneable)obj).Clone();
            }

            return obj;
        }

        // Fast path to get deserialized object when we know the type is a surrogate, to avoid the dictionary lookup in GetDeserializedObject.
        internal object GetDeserializedObjectFast(object obj)
        {
            return ((ICloneable)obj).Clone();
        }

        public object GetObjectToSerialize(object obj, Type targetType)
        {
            Type type = obj.GetType();
            if (type == targetType)
            {
                return obj;
            }

            // Fast path for then type is exactly a known type
            var (_, surrogateFactory) = this._exposedTypeToSurrogateMap.GetOrAdd(type, static (key, This) =>
            {
                // If the type is not found, check the inheritance heirarchy for a known type.
                // This ensures that the method works if the type is a proxy type generated by an ORM, for example.
                Type exposedType = This._description.GetSerializationType(key);
                if (This._exposedTypeToSurrogateMap.TryGetValue(exposedType, out var surrogateInfo))
                {
                    // Return a new instance of the surrogate.
                    return surrogateInfo;
                }
                return default;
            }, this);


            return surrogateFactory?.Invoke(obj) ?? obj;
        }

        public Func<object, object> TryGetSurrogateFactory(Type type)
        {
            if (this._exposedTypeToSurrogateMap.TryGetValue(type, out var surrogateInfo))
            {
                return surrogateInfo.surrogateFactory;
            }
            return null;
        }

#if !ASPNET_CORE
        public object GetCustomDataToExport(Type clrType, Type dataContractType)
        {
            return null;
        }

        public object GetCustomDataToExport(System.Reflection.MemberInfo memberInfo, Type dataContractType)
        {
            return null;
        }

        public void GetKnownCustomDataTypes(System.Collections.ObjectModel.Collection<Type> customDataTypes)
        {
            throw new NotImplementedException();
        }

        public Type GetReferencedTypeOnImport(string typeName, string typeNamespace, object customData)
        {
            throw new NotImplementedException();
        }

        public System.CodeDom.CodeTypeDeclaration ProcessImportedType(System.CodeDom.CodeTypeDeclaration typeDeclaration, System.CodeDom.CodeCompileUnit compileUnit)
        {
            throw new NotImplementedException();
        }
#endif
    }
}
