<Project Sdk="MSBuild.SDK.SystemWeb/4.0.107">
  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
    <RootNamespace>WebsiteMediumTrust</RootNamespace>
    <AssemblyName>WebsiteMediumTrust</AssemblyName>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <MvcBuildViews>false</MvcBuildViews>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="System.ComponentModel.DataAnnotations" />
    <Reference Include="System.Data.Services" />
    <Reference Include="System.Data.Services.Client" />
    <Reference Include="System.Runtime.Serialization" />
    <Reference Include="System.ServiceModel" />
    <Reference Include="System.ServiceModel.Web" />
    <Reference Include="System.Drawing" />
    <Reference Include="System.Web" />
    <Reference Include="System.Web.ApplicationServices" />
    <Reference Include="System.Web.DynamicData" />
    <Reference Include="System.Web.Entity" />
    <Reference Include="System.Web.Services" />
    <Reference Include="System.EnterpriseServices" />
    <Reference Include="System.Web.Mobile" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="App_Data\Templates\Northwind.ldf" />
    <None Remove="App_Data\Templates\Northwind.mdf" />
    <Content Include="App_Data\Templates\Northwind.ldf">
      <DependentUpon>Northwind.mdf</DependentUpon>
    </Content>
    <Content Include="App_Data\Templates\Northwind.mdf" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\OpenRiaServices.Hosting.Wcf.Endpoint\Framework\OpenRiaServices.Hosting.Wcf.Endpoint.csproj" />
    <ProjectReference Include="..\..\OpenRiaServices.Server.Authentication.AspNetMembership\Framework\OpenRiaServices.Server.Authentication.AspNetMembership.csproj" />
    <ProjectReference Include="..\..\OpenRiaServices.Server.EntityFrameworkCore\Framework\OpenRiaServices.Server.EntityFrameworkCore.csproj" />
    <ProjectReference Include="..\..\OpenRiaServices.Tools\Framework\OpenRiaServices.Tools.csproj" />
    <ProjectReference Include="..\..\OpenRiaServices.LinqToSql\Framework\OpenRiaServices.LinqToSql.csproj" />
    <ProjectReference Include="..\..\OpenRiaServices.Server\Framework\OpenRiaServices.Server.csproj" />
    <ProjectReference Include="..\..\OpenRiaServices.Hosting.Wcf\Framework\OpenRiaServices.Hosting.Wcf.csproj" />
    <ProjectReference Include="..\Desktop\OpenRiaServices.Common.DomainServices.Test\OpenRiaServices.Common.DomainServices.Test.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="EntityFramework" Version="6.5.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="3.1.32" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="9.0.0" />
    <PackageReference Include="System.Collections.Immutable" Version="9.0.0" />
    <PackageReference Include="System.Threading.Tasks.Extensions" Version="4.6.3" />
  </ItemGroup>
</Project>
