# Dependabot configuration
# See: https://docs.github.com/en/code-security/dependabot/working-with-dependabot/dependabot-options-reference

version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "weekly"
    # Exclude the archived projects from Dependabot scanning
    exclude-paths:
      - "src/archive/**"
