//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenRiaServices.DomainServices.Tools {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OpenRiaServices.DomainServices.Tools.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analyzing project &apos;{0}&apos; for shared source files..
        /// </summary>
        internal static string Analyzing_Project_Files {
            get {
                return ResourceManager.GetString("Analyzing_Project_Files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analyzing project &apos;{0}&apos; for project references..
        /// </summary>
        internal static string Analyzing_Project_References {
            get {
                return ResourceManager.GetString("Analyzing_Project_References", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assembly &apos;{0}&apos; could not be loaded and will be ignored.
        ///{1}.
        /// </summary>
        internal static string ClientCodeGen_Assembly_Load_Error {
            get {
                return ResourceManager.GetString("ClientCodeGen_Assembly_Load_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load types from assembly &apos;{0}&apos; so the assembly will be ignored.
        ///{1}.
        /// </summary>
        internal static string ClientCodeGen_Assembly_Load_Type_Error {
            get {
                return ResourceManager.GetString("ClientCodeGen_Assembly_Load_Type_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following attributes were not generated:.
        /// </summary>
        internal static string ClientCodeGen_Attribute_FailedToGenerate {
            get {
                return ResourceManager.GetString("ClientCodeGen_Attribute_FailedToGenerate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - {0}.
        /// </summary>
        internal static string ClientCodeGen_Attribute_FailedToGenerate_ErrorTemplate {
            get {
                return ResourceManager.GetString("ClientCodeGen_Attribute_FailedToGenerate_ErrorTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to generate the following attributes for parameter &apos;{0}&apos; due to the following errors:.
        /// </summary>
        internal static string ClientCodeGen_Attribute_Parameter_FailedToGenerate {
            get {
                return ResourceManager.GetString("ClientCodeGen_Attribute_Parameter_FailedToGenerate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The attribute &apos;{0}&apos; was not generated because a suitable attribute generator was not found.
        ///
        ///Please ensure that the attribute type follows recommended .NET Framework guidelines and meets the following requirements:
        /// - The attribute has one or more public constructors.
        /// - All public properties have public setter methods.
        ///   OR
        /// - A public constructor exists that accepts parameters matching all public properties without public setter methods.  (Matching is performed by case-insensitive name and type.).
        /// </summary>
        internal static string ClientCodeGen_Attribute_RequiresBuilder {
            get {
                return ResourceManager.GetString("ClientCodeGen_Attribute_RequiresBuilder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The attribute &apos;{0}&apos; requires a reference to System.ComponentModel.DataAnnotations in the client project &apos;{1}&apos;. Skipping generation of attribute. Please add a reference to System.ComponentModel.DataAnnotations to ensure generation of the attribute..
        /// </summary>
        internal static string ClientCodeGen_Attribute_RequiresDataAnnotations {
            get {
                return ResourceManager.GetString("ClientCodeGen_Attribute_RequiresDataAnnotations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The attribute &apos;{0}&apos; is not visible in the client project &apos;{1}&apos;. Are you missing an assembly reference?.
        /// </summary>
        internal static string ClientCodeGen_Attribute_RequiresShared {
            get {
                return ResourceManager.GetString("ClientCodeGen_Attribute_RequiresShared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The attribute &apos;{0}&apos; references a method &apos;{1}&apos; on type &apos;{2}&apos; that is not accessible in the client project &apos;{3}&apos;..
        /// </summary>
        internal static string ClientCodeGen_Attribute_RequiresShared_Method {
            get {
                return ResourceManager.GetString("ClientCodeGen_Attribute_RequiresShared_Method", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The attribute &apos;{0}&apos; in assembly &apos;{1}&apos;
        /// was not generated in the proxy classes for client project &apos;{2}&apos;
        /// because there was insufficient information to determine whether it is visible to the client project.
        /// If this attribute type is intended to be used in shared code, avoid the use of
        /// automatic properties, provide at least a default constructor,
        /// and be sure a PDB is available for analysis..
        /// </summary>
        internal static string ClientCodeGen_Attribute_RequiresShared_NoPDB {
            get {
                return ResourceManager.GetString("ClientCodeGen_Attribute_RequiresShared_NoPDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The attribute &apos;{0}&apos; references a property &apos;{1}&apos; on type &apos;{2}&apos; that is not accessible in the client project &apos;{3}&apos;..
        /// </summary>
        internal static string ClientCodeGen_Attribute_RequiresShared_Property {
            get {
                return ResourceManager.GetString("ClientCodeGen_Attribute_RequiresShared_Property", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The attribute &apos;{0}&apos; references type &apos;{1}&apos; that is not accessible in the client project &apos;{2}&apos;. If you would like the attribute to be generated, make sure the assembly containing the attribute is referenced on the client..
        /// </summary>
        internal static string ClientCodeGen_Attribute_RequiresShared_Type {
            get {
                return ResourceManager.GetString("ClientCodeGen_Attribute_RequiresShared_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The attribute &apos;{0}&apos; references type &apos;{1}&apos; from assembly &apos;{2}&apos;. The type is not visible to the client project &apos;{3}&apos; because either a PDB file does not exist or the type does not contain user-defined code..
        /// </summary>
        internal static string ClientCodeGen_Attribute_RequiresShared_Type_NoPDB {
            get {
                return ResourceManager.GetString("ClientCodeGen_Attribute_RequiresShared_Type_NoPDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An exception occurred generating the &apos;{1}&apos; property on attribute of type &apos;{0}&apos;..
        /// </summary>
        internal static string ClientCodeGen_Attribute_ThrewException {
            get {
                return ResourceManager.GetString("ClientCodeGen_Attribute_ThrewException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}  The attribute could not be generated for the &apos;{1}&apos; method of the &apos;{2}&apos; class.  Exception message: {3}.
        /// </summary>
        internal static string ClientCodeGen_Attribute_ThrewException_CodeMethod {
            get {
                return ResourceManager.GetString("ClientCodeGen_Attribute_ThrewException_CodeMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}  The attribute could not be generated for the &apos;{1}&apos; parameter to the &apos;{2}&apos; method of the &apos;{3}&apos; class.  Exception message: {4}.
        /// </summary>
        internal static string ClientCodeGen_Attribute_ThrewException_CodeMethodParameter {
            get {
                return ResourceManager.GetString("ClientCodeGen_Attribute_ThrewException_CodeMethodParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}  The attribute could not be generated for the &apos;{1}&apos; type.  Exception message: {2}.
        /// </summary>
        internal static string ClientCodeGen_Attribute_ThrewException_CodeType {
            get {
                return ResourceManager.GetString("ClientCodeGen_Attribute_ThrewException_CodeType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}  The attribute could not be generated for the &apos;{1}&apos; member of the &apos;{2}&apos; type.  Exception message: {3}.
        /// </summary>
        internal static string ClientCodeGen_Attribute_ThrewException_CodeTypeMember {
            get {
                return ResourceManager.GetString("ClientCodeGen_Attribute_ThrewException_CodeTypeMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The property &apos;{0}&apos; in type &apos;{1}&apos; is marked with both IncludeAttribute and ExcludeAttribute.  Ignoring IncludeAttribute. Please remove the ExcludeAttribute if you want the association in the generated code..
        /// </summary>
        internal static string ClientCodeGen_Cannot_Have_Include_And_Exclude {
            get {
                return ResourceManager.GetString("ClientCodeGen_Cannot_Have_Include_And_Exclude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Complex Type &apos;{0}&apos; already exists in another assembly. Complex Types cannot be defined in multiple assemblies..
        /// </summary>
        internal static string ClientCodeGen_ComplexTypesCannotBeShared_Reference {
            get {
                return ResourceManager.GetString("ClientCodeGen_ComplexTypesCannotBeShared_Reference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copying file &apos;{0}&apos; to &apos;{1}&apos;..
        /// </summary>
        internal static string ClientCodeGen_Copying_File {
            get {
                return ResourceManager.GetString("ClientCodeGen_Copying_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting previously generated file &apos;{0}&apos;.
        /// </summary>
        internal static string ClientCodeGen_Deleting_Orphan {
            get {
                return ResourceManager.GetString("ClientCodeGen_Deleting_Orphan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting empty folder &apos;{0}&apos;.
        /// </summary>
        internal static string ClientCodeGen_Deleting_Orphan_Folder {
            get {
                return ResourceManager.GetString("ClientCodeGen_Deleting_Orphan_Folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DomainOperationEntry &apos;{0}&apos; in DomainService &apos;{1}&apos; will not be generated because it uses the Enum type &apos;{2}&apos;.  {3}.
        /// </summary>
        internal static string ClientCodeGen_Domain_Op_Enum_Error {
            get {
                return ResourceManager.GetString("ClientCodeGen_Domain_Op_Enum_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot generate DomainService &apos;{0}&apos;. Nested DomainService types are not supported..
        /// </summary>
        internal static string ClientCodeGen_DomainService_CannotBeNested {
            get {
                return ResourceManager.GetString("ClientCodeGen_DomainService_CannotBeNested", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CodeProcessor type &apos;{0}&apos; defined in DomainIdentifier attribute on type &apos;{1}&apos; threw an Exception: {2}.
        /// </summary>
        internal static string ClientCodeGen_DomainService_CodeProcessor_ExceptionCaught {
            get {
                return ResourceManager.GetString("ClientCodeGen_DomainService_CodeProcessor_ExceptionCaught", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CodeProcessor type &apos;{0}&apos; defined in DomainIdentifier attribute on type &apos;{1}&apos; must have a constructor accepting one parameter of type &apos;{2}&apos;..
        /// </summary>
        internal static string ClientCodeGen_DomainService_CodeProcessor_InvalidConstructorSignature {
            get {
                return ResourceManager.GetString("ClientCodeGen_DomainService_CodeProcessor_InvalidConstructorSignature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type &apos;{0}&apos; defined in DomainIdentifier attribute on type &apos;{1}&apos; is not a valid CodeProcessor implementation..
        /// </summary>
        internal static string ClientCodeGen_DomainService_CodeProcessor_NotValidType {
            get {
                return ResourceManager.GetString("ClientCodeGen_DomainService_CodeProcessor_NotValidType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DomainService &apos;{0}&apos; derives from DomainService &apos;{1}&apos;. Only the leaf DomainService in the inheritance hierarchy may have the EnableClientAccessAttribute..
        /// </summary>
        internal static string ClientCodeGen_DomainService_Inheritance_Not_Allowed {
            get {
                return ResourceManager.GetString("ClientCodeGen_DomainService_Inheritance_Not_Allowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DomainService &apos;{0}&apos; does not contain any public domain operations..
        /// </summary>
        internal static string ClientCodeGen_EmptyDomainService {
            get {
                return ResourceManager.GetString("ClientCodeGen_EmptyDomainService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The entity type &apos;{0}&apos; already exists in another assembly. Entity types cannot be defined in multiple assemblies..
        /// </summary>
        internal static string ClientCodeGen_EntityTypesCannotBeShared_Reference {
            get {
                return ResourceManager.GetString("ClientCodeGen_EntityTypesCannotBeShared_Reference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not delete folder &apos;{0}&apos;.  {1}.
        /// </summary>
        internal static string ClientCodeGen_Failed_Delete_Folder {
            get {
                return ResourceManager.GetString("ClientCodeGen_Failed_Delete_Folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load the {0} assembly using the path {1}, code generation might fail. Is the server project missing a reference to OpenRiaServices?.
        /// </summary>
        internal static string ClientCodeGen_Failed_Loading_OpenRiaServices_Assembly {
            get {
                return ResourceManager.GetString("ClientCodeGen_Failed_Loading_OpenRiaServices_Assembly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load one or more types from assembly &apos;{0}&apos;: {1}.  Continuing with the types that loaded successfully..
        /// </summary>
        internal static string ClientCodeGen_Failed_To_Load {
            get {
                return ResourceManager.GetString("ClientCodeGen_Failed_To_Load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find necessary input file &apos;{0}&apos;..
        /// </summary>
        internal static string ClientCodeGen_Input_Assembly_Not_Found {
            get {
                return ResourceManager.GetString("ClientCodeGen_Input_Assembly_Not_Found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code cannot be generated for the DomainService &apos;{0}&apos; because it isn&apos;t marked with EnableClientAccessAttribute..
        /// </summary>
        internal static string ClientCodeGen_InvalidDomainServiceType {
            get {
                return ResourceManager.GetString("ClientCodeGen_InvalidDomainServiceType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The server project does not contain a reference to {0}, code generation might fail. Is the server project missing a reference to OpenRiaServices?.
        /// </summary>
        internal static string ClientCodeGen_Missing_OpenRiaServices_Reference {
            get {
                return ResourceManager.GetString("ClientCodeGen_Missing_OpenRiaServices_Reference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type &apos;{0}&apos; must appear inside a namespace..
        /// </summary>
        internal static string ClientCodeGen_Namespace_Required {
            get {
                return ResourceManager.GetString("ClientCodeGen_Namespace_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to generate DomainService &apos;{0}&apos; due to a naming conflict with an existing member.  DomainOperationEntry &apos;{1}&apos; conflicts with an auto-generated property with the same name.  Consider renaming..
        /// </summary>
        internal static string ClientCodeGen_NamingCollision_MemberAlreadyExists {
            get {
                return ResourceManager.GetString("ClientCodeGen_NamingCollision_MemberAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;{0}&apos; project must be built before client proxy classes can be generated..
        /// </summary>
        internal static string ClientCodeGen_No_Input_Assemblies {
            get {
                return ResourceManager.GetString("ClientCodeGen_No_Input_Assemblies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The client proxy task generated or is reusing existing copies of these files:{0}.
        /// </summary>
        internal static string ClientCodeGen_OutputFiles_Are {
            get {
                return ResourceManager.GetString("ClientCodeGen_OutputFiles_Are", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property &apos;{0}.{1}&apos; will not be generated because it uses the Enum type &apos;{2}&apos;.  {3}.
        /// </summary>
        internal static string ClientCodeGen_Property_Enum_Error {
            get {
                return ResourceManager.GetString("ClientCodeGen_Property_Enum_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The property &apos;{0}&apos; in entity type &apos;{1}&apos; cannot be generated because its type &apos;{2}&apos; is not visible in the client project &apos;{3}&apos;. Are you missing an assembly reference?.
        /// </summary>
        internal static string ClientCodeGen_PropertyType_Not_Shared {
            get {
                return ResourceManager.GetString("ClientCodeGen_PropertyType_Not_Shared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are usigned the signed code generation but the server assemblies are unsigned, consider using the unsigned code generation package instead since code generation might fail..
        /// </summary>
        internal static string ClientCodeGen_SignedTools_UnsignedServer {
            get {
                return ResourceManager.GetString("ClientCodeGen_SignedTools_UnsignedServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skipping code generation because existing file &apos;{0}&apos; is current..
        /// </summary>
        internal static string ClientCodeGen_Skipping_CodeGen {
            get {
                return ResourceManager.GetString("ClientCodeGen_Skipping_CodeGen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skipping copy because existing file &apos;{0}&apos; is current..
        /// </summary>
        internal static string ClientCodeGen_Skipping_Copy {
            get {
                return ResourceManager.GetString("ClientCodeGen_Skipping_Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The validation attribute &apos;{0}&apos; contains ErrorMessageResourceType=&apos;{1}&apos; and ErrorMessageResourceName=&apos;{2}&apos;.  You must specify values for both or neither..
        /// </summary>
        internal static string ClientCodeGen_ValidationAttribute_Requires_ResourceType_And_Name {
            get {
                return ResourceManager.GetString("ClientCodeGen_ValidationAttribute_Requires_ResourceType_And_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The validation attribute &apos;{0}&apos; contains ErrorMessageResourceName=&apos;{1}&apos; which was not found on declared ErrorMessageResourceType &apos;{2}&apos;..
        /// </summary>
        internal static string ClientCodeGen_ValidationAttribute_ResourcePropertyNotFound {
            get {
                return ResourceManager.GetString("ClientCodeGen_ValidationAttribute_ResourcePropertyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected exception thrown before code gen could be started, this indicates a serious error which might be caused by missing or corrupt assemblies..
        /// </summary>
        internal static string ClientCodeGenDispatecher_Threw_Exception_Before_Generate {
            get {
                return ResourceManager.GetString("ClientCodeGenDispatecher_Threw_Exception_Before_Generate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;ClientProxyGenerator.Initialize&apos; must be called before use..
        /// </summary>
        internal static string ClientProxyGenerator_Initialize_Not_Called {
            get {
                return ResourceManager.GetString("ClientProxyGenerator_Initialize_Not_Called", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The requested code generator &apos;{0}&apos; cannot be used because it does not implement &apos;IDomainServiceClientCodeGenerator&apos;..
        /// </summary>
        internal static string Code_Generator_Incorrect_Type {
            get {
                return ResourceManager.GetString("Code_Generator_Incorrect_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The requested code generator &apos;{0}&apos; cannot be instantiated:
        ///{0}.
        /// </summary>
        internal static string Code_Generator_Instantiation_Error {
            get {
                return ResourceManager.GetString("Code_Generator_Instantiation_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No code generator named &apos;{0}&apos; is available for &apos;{1}&apos;.
        ///If a generator with this name exists elsewhere, add a reference to its assembly to the
        ///&apos;{2}&apos; project.
        ///Otherwise, manually edit the &apos;{3}&apos; project
        ///to add a &lt;OpenRiaClientCodeGeneratorName&gt; property to name a valid generator.
        ///To specify the default generator add this property:
        ///  &lt;OpenRiaClientCodeGeneratorName&gt;{4}&lt;/OpenRiaClientCodeGeneratorName&gt;
        ///.
        /// </summary>
        internal static string Code_Generator_Not_Found {
            get {
                return ResourceManager.GetString("Code_Generator_Not_Found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;{0}&apos; class..
        /// </summary>
        internal static string CodeGen_Complex_Class_Summary_Comment {
            get {
                return ResourceManager.GetString("CodeGen_Complex_Class_Summary_Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A new container instance..
        /// </summary>
        internal static string CodeGen_CreateEntityContainer_Method_Returns_Comment {
            get {
                return ResourceManager.GetString("CodeGen_CreateEntityContainer_Method_Returns_Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creates a new EntityContainer for this DomainContext&apos;s EntitySets..
        /// </summary>
        internal static string CodeGen_CreateEntityContainer_Method_Summary_Comment {
            get {
                return ResourceManager.GetString("CodeGen_CreateEntityContainer_Method_Summary_Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initializes a new instance of the &lt;see cref=&quot;{0}&quot;/&gt; class..
        /// </summary>
        internal static string CodeGen_Default_Constructor_Summary_Comments {
            get {
                return ResourceManager.GetString("CodeGen_Default_Constructor_Summary_Comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invokes the &apos;{0}&apos; method of the specified &lt;see cref=&quot;{1}&quot;/&gt; entity..
        /// </summary>
        internal static string CodeGen_DomainClient_Custom_Method_Summary_Comment {
            get {
                return ResourceManager.GetString("CodeGen_DomainClient_Custom_Method_Summary_Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The DomainContext corresponding to the &apos;{0}&apos; DomainService..
        /// </summary>
        internal static string CodeGen_DomainContext_Class_Summary_Comment {
            get {
                return ResourceManager.GetString("CodeGen_DomainContext_Class_Summary_Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &lt;see cref=&quot;{0}&quot;/&gt; entity instance..
        /// </summary>
        internal static string CodeGen_DomainContext_Custom_Method_Entity_Parameter_Comment {
            get {
                return ResourceManager.GetString("CodeGen_DomainContext_Custom_Method_Entity_Parameter_Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value for the &apos;{0}&apos; parameter for this action..
        /// </summary>
        internal static string CodeGen_DomainContext_Custom_Method_Parameter_Comment {
            get {
                return ResourceManager.GetString("CodeGen_DomainContext_Custom_Method_Parameter_Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Callback to invoke when the operation completes..
        /// </summary>
        internal static string CodeGen_DomainContext_Invoke_Method_Callback_Parameter_Comment {
            get {
                return ResourceManager.GetString("CodeGen_DomainContext_Invoke_Method_Callback_Parameter_Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A cancellation token that can be used to cancel the work.
        /// </summary>
        internal static string CodeGen_DomainContext_Invoke_Method_CancellationToken_Parameter_Comment {
            get {
                return ResourceManager.GetString("CodeGen_DomainContext_Invoke_Method_CancellationToken_Parameter_Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value for the &apos;{0}&apos; parameter of this action..
        /// </summary>
        internal static string CodeGen_DomainContext_Invoke_Method_Parameter_Comment {
            get {
                return ResourceManager.GetString("CodeGen_DomainContext_Invoke_Method_Parameter_Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asynchronously invokes the &apos;{0}&apos; method of the DomainService..
        /// </summary>
        internal static string CodeGen_DomainContext_Invoke_Method_Summary_Comment {
            get {
                return ResourceManager.GetString("CodeGen_DomainContext_Invoke_Method_Summary_Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value to pass to the callback.  It can be &lt;c&gt;null&lt;/c&gt;..
        /// </summary>
        internal static string CodeGen_DomainContext_Invoke_Method_UserState_Parameter_Comment {
            get {
                return ResourceManager.GetString("CodeGen_DomainContext_Invoke_Method_UserState_Parameter_Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An operation instance that can be used to manage the asynchronous request..
        /// </summary>
        internal static string CodeGen_DomainContext_Invoke_Returns_Comment {
            get {
                return ResourceManager.GetString("CodeGen_DomainContext_Invoke_Returns_Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optional state object..
        /// </summary>
        internal static string CodeGen_DomainContext_ServiceContract_Begin_Method_AsyncState_Parameter_Comment {
            get {
                return ResourceManager.GetString("CodeGen_DomainContext_ServiceContract_Begin_Method_AsyncState_Parameter_Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Callback to invoke on completion..
        /// </summary>
        internal static string CodeGen_DomainContext_ServiceContract_Begin_Method_Callback_Parameter_Comment {
            get {
                return ResourceManager.GetString("CodeGen_DomainContext_ServiceContract_Begin_Method_Callback_Parameter_Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value for the &apos;{0}&apos; parameter of this action..
        /// </summary>
        internal static string CodeGen_DomainContext_ServiceContract_Begin_Method_Parameter_Comment {
            get {
                return ResourceManager.GetString("CodeGen_DomainContext_ServiceContract_Begin_Method_Parameter_Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An IAsyncResult that can be used to monitor the request..
        /// </summary>
        internal static string CodeGen_DomainContext_ServiceContract_Begin_Method_Returns_Comment {
            get {
                return ResourceManager.GetString("CodeGen_DomainContext_ServiceContract_Begin_Method_Returns_Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asynchronously invokes the &apos;{0}&apos; operation..
        /// </summary>
        internal static string CodeGen_DomainContext_ServiceContract_Begin_Method_Summary_Comment {
            get {
                return ResourceManager.GetString("CodeGen_DomainContext_ServiceContract_Begin_Method_Summary_Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The change-set to submit..
        /// </summary>
        internal static string CodeGen_DomainContext_ServiceContract_Begin_SubmitMethod_Changeset_Parameter_Comment {
            get {
                return ResourceManager.GetString("CodeGen_DomainContext_ServiceContract_Begin_SubmitMethod_Changeset_Parameter_Comm" +
                        "ent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The IAsyncResult returned from &apos;{0}&apos;..
        /// </summary>
        internal static string CodeGen_DomainContext_ServiceContract_End_Method_Parameter_Comment {
            get {
                return ResourceManager.GetString("CodeGen_DomainContext_ServiceContract_End_Method_Parameter_Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;{0}&apos; returned from the &apos;{1}&apos; operation..
        /// </summary>
        internal static string CodeGen_DomainContext_ServiceContract_End_Method_Returns_Comment {
            get {
                return ResourceManager.GetString("CodeGen_DomainContext_ServiceContract_End_Method_Returns_Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completes the asynchronous operation begun by &apos;{0}&apos;..
        /// </summary>
        internal static string CodeGen_DomainContext_ServiceContract_End_Method_Summary_Comment {
            get {
                return ResourceManager.GetString("CodeGen_DomainContext_ServiceContract_End_Method_Summary_Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The collection of change-set entry elements returned from &apos;SubmitChanges&apos;..
        /// </summary>
        internal static string CodeGen_DomainContext_ServiceContract_End_SubmitMethod_Returns_Comment {
            get {
                return ResourceManager.GetString("CodeGen_DomainContext_ServiceContract_End_SubmitMethod_Returns_Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service contract for the &apos;{0}&apos; DomainService..
        /// </summary>
        internal static string CodeGen_DomainContext_ServiceContract_Summary_Comment {
            get {
                return ResourceManager.GetString("CodeGen_DomainContext_ServiceContract_Summary_Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets a value indicating whether the &apos;{0}&apos; method can be invoked on this entity..
        /// </summary>
        internal static string CodeGen_Entity_CanInvoke_Property_Summary_Comment {
            get {
                return ResourceManager.GetString("CodeGen_Entity_CanInvoke_Property_Summary_Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &lt;see cref=&quot;{0}&quot;/&gt; context..
        /// </summary>
        internal static string CodeGen_Entity_Class_Context_Summary_Comment {
            get {
                return ResourceManager.GetString("CodeGen_Entity_Class_Context_Summary_Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This entity is shared between the following contexts:.
        /// </summary>
        internal static string CodeGen_Entity_Class_Shared_Summary_Comment {
            get {
                return ResourceManager.GetString("CodeGen_Entity_Class_Shared_Summary_Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;{0}&apos; entity class..
        /// </summary>
        internal static string CodeGen_Entity_Class_Summary_Comment {
            get {
                return ResourceManager.GetString("CodeGen_Entity_Class_Summary_Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets the collection of associated &lt;see cref=&quot;{0}&quot;/&gt; entity instances..
        /// </summary>
        internal static string CodeGen_Entity_Collection_Association_Property_Summary_Comment {
            get {
                return ResourceManager.GetString("CodeGen_Entity_Collection_Association_Property_Summary_Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value to pass to the server method&apos;s &apos;{0}&apos; parameter..
        /// </summary>
        internal static string CodeGen_Entity_Custom_Method_Parameter_Comment {
            get {
                return ResourceManager.GetString("CodeGen_Entity_Custom_Method_Parameter_Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invokes the &apos;{0}&apos; action on this entity..
        /// </summary>
        internal static string CodeGen_Entity_Custom_Method_Summary_Comment {
            get {
                return ResourceManager.GetString("CodeGen_Entity_Custom_Method_Summary_Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets a value indicating whether the &apos;{0}&apos; action has been invoked on this entity..
        /// </summary>
        internal static string CodeGen_Entity_IsInvoked_Property_Summary_Comment {
            get {
                return ResourceManager.GetString("CodeGen_Entity_IsInvoked_Property_Summary_Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets or sets the &apos;{0}&apos; value..
        /// </summary>
        internal static string CodeGen_Entity_Property_Summary_Comment {
            get {
                return ResourceManager.GetString("CodeGen_Entity_Property_Summary_Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets or sets the associated &lt;see cref=&quot;{0}&quot;/&gt; entity..
        /// </summary>
        internal static string CodeGen_Entity_Singleton_Association_Property_Summary_Comment {
            get {
                return ResourceManager.GetString("CodeGen_Entity_Singleton_Association_Property_Summary_Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets the associated &lt;see cref=&quot;{0}&quot;/&gt; entity..
        /// </summary>
        internal static string CodeGen_Entity_Singleton_Association_ReadOnly_Property_Summary_Comment {
            get {
                return ResourceManager.GetString("CodeGen_Entity_Singleton_Association_ReadOnly_Property_Summary_Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets the set of &lt;see cref=&quot;{0}&quot;/&gt; entity instances that have been loaded into this &lt;see cref=&quot;{1}&quot;/&gt; instance..
        /// </summary>
        internal static string CodeGen_EntitySet_Property_Summary_Comment {
            get {
                return ResourceManager.GetString("CodeGen_EntitySet_Property_Summary_Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RIA client proxy class generation finished in {0} seconds..
        /// </summary>
        internal static string CodeGen_Execution_Time {
            get {
                return ResourceManager.GetString("CodeGen_Execution_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generating proxy classes for the DomainService &apos;{0}&apos;..
        /// </summary>
        internal static string CodeGen_Generating_DomainService {
            get {
                return ResourceManager.GetString("CodeGen_Generating_DomainService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RIA client proxy class generation starting for project &apos;{0}&apos;..
        /// </summary>
        internal static string CodeGen_Generating_Proxies {
            get {
                return ResourceManager.GetString("CodeGen_Generating_Proxies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generating WebContext class..
        /// </summary>
        internal static string CodeGen_Generating_WebContext {
            get {
                return ResourceManager.GetString("CodeGen_Generating_WebContext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An object instance that uniquely identifies this entity instance..
        /// </summary>
        internal static string CodeGen_GetIdentify_Method_Returns_Comment {
            get {
                return ResourceManager.GetString("CodeGen_GetIdentify_Method_Returns_Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Computes a value from the key fields that uniquely identifies this entity instance..
        /// </summary>
        internal static string CodeGen_GetIdentify_Method_Summary_Comment {
            get {
                return ResourceManager.GetString("CodeGen_GetIdentify_Method_Summary_Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shared file analysis cannot be done on assembly &apos;{0}&apos; because it has no corresponding PDB file.
        ///Change its project file to set DebugType to &apos;full&apos; or &apos;pdbonly&apos; if you intend to share code..
        /// </summary>
        internal static string CodeGen_No_Pdb {
            get {
                return ResourceManager.GetString("CodeGen_No_Pdb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value for the &apos;{0}&apos; parameter of the query..
        /// </summary>
        internal static string CodeGen_Query_Method_Parameter_Comment {
            get {
                return ResourceManager.GetString("CodeGen_Query_Method_Parameter_Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An EntityQuery that can be loaded to retrieve &lt;see cref=&quot;{0}&quot;/&gt; entity instances..
        /// </summary>
        internal static string CodeGen_Query_Method_Returns_Comment {
            get {
                return ResourceManager.GetString("CodeGen_Query_Method_Returns_Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files visible to both the client and the server are:{0}.
        /// </summary>
        internal static string CodeGen_Shared_Files {
            get {
                return ResourceManager.GetString("CodeGen_Shared_Files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The code generator &apos;{0}&apos; encountered a fatal exception and could not generate code for project &apos;{1}&apos;:
        ///{2}.
        /// </summary>
        internal static string CodeGenerator_Threw_Exception {
            get {
                return ResourceManager.GetString("CodeGenerator_Threw_Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;summary&gt;
        ///This method is invoked from the constructor once initialization is complete and
        ///can be used for further object setup.
        ///&lt;/summary&gt;.
        /// </summary>
        internal static string CommentOnCreated {
            get {
                return ResourceManager.GetString("CommentOnCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting file {0} because no client proxy classes have been generated..
        /// </summary>
        internal static string Deleting_Empty_File {
            get {
                return ResourceManager.GetString("Deleting_Empty_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The DomainClient instance to use for this DomainContext..
        /// </summary>
        internal static string EntityCodeGen_ConstructorComments_Param_DomainClient {
            get {
                return ResourceManager.GetString("EntityCodeGen_ConstructorComments_Param_DomainClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} service URI..
        /// </summary>
        internal static string EntityCodeGen_ConstructorComments_Param_ServiceUri {
            get {
                return ResourceManager.GetString("EntityCodeGen_ConstructorComments_Param_ServiceUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initializes a new instance of the &lt;see cref=&quot;{0}&quot;/&gt; class with the specified &lt;paramref name=&quot;domainClient&quot;/&gt;..
        /// </summary>
        internal static string EntityCodeGen_ConstructorComments_Summary_DomainClientAccumulating {
            get {
                return ResourceManager.GetString("EntityCodeGen_ConstructorComments_Summary_DomainClientAccumulating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets an EntityQuery instance that can be used to load &lt;see cref=&quot;{0}&quot;/&gt; entity instances using the &apos;{1}&apos; query..
        /// </summary>
        internal static string EntityCodeGen_ConstructorComments_Summary_DomainContext {
            get {
                return ResourceManager.GetString("EntityCodeGen_ConstructorComments_Summary_DomainContext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initializes a new instance of the &lt;see cref=&quot;{0}&quot;/&gt; class with the specified service URI..
        /// </summary>
        internal static string EntityCodeGen_ConstructorComments_Summary_ServiceUri {
            get {
                return ResourceManager.GetString("EntityCodeGen_ConstructorComments_Summary_ServiceUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The custom method named &apos;{0}&apos; associated with entity type &apos;{1}&apos; is defined more than once in the &apos;{2}&apos; and &apos;{3}&apos; DomainService classes..
        /// </summary>
        internal static string EntityCodeGen_DuplicateCustomMethodName {
            get {
                return ResourceManager.GetString("EntityCodeGen_DuplicateCustomMethodName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property &apos;{0}.{1}&apos; is marked as a key property and is of type &apos;{2}&apos;, which is not a supported type for a key member..
        /// </summary>
        internal static string EntityCodeGen_EntityKey_KeyTypeNotSupported {
            get {
                return ResourceManager.GetString("EntityCodeGen_EntityKey_KeyTypeNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The property &apos;{0}.{1}&apos; is marked as a key property, but it&apos;s not serializable. Are you missing DataMemberAttribute?.
        /// </summary>
        internal static string EntityCodeGen_EntityKey_PropertyNotSerializable {
            get {
                return ResourceManager.GetString("EntityCodeGen_EntityKey_PropertyNotSerializable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generating custom method guard property &apos;{0}&apos;....
        /// </summary>
        internal static string EntityCodeGen_Generating_GuardProperty {
            get {
                return ResourceManager.GetString("EntityCodeGen_Generating_GuardProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generating update method for guard properties....
        /// </summary>
        internal static string EntityCodeGen_Generating_GuardUpdateMethod {
            get {
                return ResourceManager.GetString("EntityCodeGen_Generating_GuardUpdateMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generating domain invoke method &apos;{0}&apos;....
        /// </summary>
        internal static string EntityCodeGen_Generating_InvokeMethod {
            get {
                return ResourceManager.GetString("EntityCodeGen_Generating_InvokeMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to generate entity &apos;{0}&apos; due to a naming conflict with an existing member.  Custom method &apos;{1}&apos; conflicts with a field with the same name.  Consider renaming..
        /// </summary>
        internal static string EntityCodeGen_NamingCollision_EntityCustomMethodNameAlreadyExists {
            get {
                return ResourceManager.GetString("EntityCodeGen_NamingCollision_EntityCustomMethodNameAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is a RoundtripOriginalAttribute on derived type &apos;{0}&apos; but not on base type &apos;{1}&apos;. RoundtripOriginalAttribute needs to be on the least derived entity type in an inheritance hierarchy..
        /// </summary>
        internal static string EntityCodeGen_RoundtripOriginalOnBaseType {
            get {
                return ResourceManager.GetString("EntityCodeGen_RoundtripOriginalOnBaseType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sharing entity types within an inheritance hierarchy is not allowed unless all DomainServices expose the same least derived entity. Entity &apos;{0}&apos; is the least derived entity on DomainService &apos;{1}&apos;,  Entity &apos;{2}&apos; is the least derived Entity on DomainService &apos;{3}&apos;, and Entity &apos;{4}&apos; is exposed from both DomainServices..
        /// </summary>
        internal static string EntityCodeGen_SharedEntityMustBeLeastDerived {
            get {
                return ResourceManager.GetString("EntityCodeGen_SharedEntityMustBeLeastDerived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Enum type is not visible to the client and belongs to the System namespace.  Are you missing an assembly reference?.
        /// </summary>
        internal static string Enum_Type_Cannot_Gen_System {
            get {
                return ResourceManager.GetString("Enum_Type_Cannot_Gen_System", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Enum type must be public and cannot be nested..
        /// </summary>
        internal static string Enum_Type_Must_Be_Public {
            get {
                return ResourceManager.GetString("Enum_Type_Must_Be_Public", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to copy file &apos;{0}&apos; to &apos;{1}&apos;. {2}.
        /// </summary>
        internal static string Failed_To_Copy_File {
            get {
                return ResourceManager.GetString("Failed_To_Copy_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following exception occurred creating the MEF composition container:
        ///{0}
        ///The default code generator will be used..
        /// </summary>
        internal static string Failed_To_Create_Composition_Container {
            get {
                return ResourceManager.GetString("Failed_To_Create_Composition_Container", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create folder &apos;{0}&apos;.{1}.
        /// </summary>
        internal static string Failed_To_Create_Folder {
            get {
                return ResourceManager.GetString("Failed_To_Create_Folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to delete file &apos;{0}&apos;..
        /// </summary>
        internal static string Failed_To_Delete_File {
            get {
                return ResourceManager.GetString("Failed_To_Delete_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not delete file &apos;{0}&apos;. {1}.
        /// </summary>
        internal static string Failed_To_Delete_File_Error {
            get {
                return ResourceManager.GetString("Failed_To_Delete_File_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to modify the read-only attribute of file &apos;{0}&apos;.{1}.
        /// </summary>
        internal static string Failed_To_Modify_ReadOnly {
            get {
                return ResourceManager.GetString("Failed_To_Modify_ReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error was encountered attempting to read the PDB file for &apos;{0}&apos; so it will not be possible to detect shared files in that assembly.  {1}.
        /// </summary>
        internal static string Failed_To_Open_PDB {
            get {
                return ResourceManager.GetString("Failed_To_Open_PDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error was encountered attempting to open project &apos;{0}&apos;. {1}.
        /// </summary>
        internal static string Failed_To_Open_Project {
            get {
                return ResourceManager.GetString("Failed_To_Open_Project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to read the contents of &apos;{0}&apos; from Visual Studio..
        /// </summary>
        internal static string Failed_To_Read_File_From_VS {
            get {
                return ResourceManager.GetString("Failed_To_Read_File_From_VS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to move/rename file &apos;{0}&apos; to &apos;{1}&apos;. {2}.
        /// </summary>
        internal static string Failed_To_Rename_File {
            get {
                return ResourceManager.GetString("Failed_To_Rename_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to write file &apos;{0}&apos;. {1}.
        /// </summary>
        internal static string Failed_To_Write_File {
            get {
                return ResourceManager.GetString("Failed_To_Write_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to write the generated contents of &apos;{0}&apos; to Visual Studio..
        /// </summary>
        internal static string Failed_To_Write_File_To_VS {
            get {
                return ResourceManager.GetString("Failed_To_Write_File_To_VS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was a problem initializing the HttpRuntime..
        /// </summary>
        internal static string HttpRuntimeInitializationError {
            get {
                return ResourceManager.GetString("HttpRuntimeInitializationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple custom code generators are available for {0}:
        ///{1}Please set the OpenRiaClientCodeGeneratorName property in the client project to select which of these you wish to use.
        ///.
        /// </summary>
        internal static string Multiple_Custom_Code_Generators {
            get {
                return ResourceManager.GetString("Multiple_Custom_Code_Generators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple custom code generators are available for &apos;{0}&apos;:
        ///{1}The default generator will be used because none was specified.
        ///To specify one manually edit the &apos;{2}&apos; project
        ///and add a property like this:
        ///  &lt;OpenRiaClientCodeGeneratorName&gt;{3}&lt;/OpenRiaClientCodeGeneratorName&gt;
        ///To specify the default generator add this property:
        ///  &lt;OpenRiaClientCodeGeneratorName&gt;{4}&lt;/OpenRiaClientCodeGeneratorName&gt;.
        /// </summary>
        internal static string Multiple_Custom_Code_Generators_Using_Default {
            get {
                return ResourceManager.GetString("Multiple_Custom_Code_Generators_Using_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple code generators named &apos;{0}&apos; are available for &apos;{1}&apos;:
        ///{2}Remove all but one from &apos;{3}&apos;,
        ///modify them to have unique names,
        ///or manually edit the &apos;{4}&apos; project
        ///to add a property that fully qualifies one, like this:
        ///    &lt;OpenRiaClientCodeGeneratorName&gt;{5}&lt;/OpenRiaClientCodeGeneratorName&gt;.
        /// </summary>
        internal static string Multiple_Named_Code_Generators {
            get {
                return ResourceManager.GetString("Multiple_Named_Code_Generators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;ClientProxyCodeGenerationOptions.Language&apos; property cannot be null or empty..
        /// </summary>
        internal static string Null_Language_Property {
            get {
                return ResourceManager.GetString("Null_Language_Property", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Logger property cannot be null..
        /// </summary>
        internal static string Null_Logger_Property {
            get {
                return ResourceManager.GetString("Null_Logger_Property", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The project &apos;{0}&apos; does not exist..
        /// </summary>
        internal static string Project_Does_Not_Exist {
            get {
                return ResourceManager.GetString("Project_Does_Not_Exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The project &apos;{0}&apos; contains project references to:.
        /// </summary>
        internal static string Project_References_Found {
            get {
                return ResourceManager.GetString("Project_References_Found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProjectPath property is required when relative paths are used..
        /// </summary>
        internal static string ProjectPath_Argument_Required {
            get {
                return ResourceManager.GetString("ProjectPath_Argument_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type &apos;{0}&apos; does not contain a property named &apos;{1}&apos;..
        /// </summary>
        internal static string Property_Not_Found {
            get {
                return ResourceManager.GetString("Property_Not_Found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extensibility Method Definitions.
        /// </summary>
        internal static string Region_ExtensibilityMethodDefinitions {
            get {
                return ResourceManager.GetString("Region_ExtensibilityMethodDefinitions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Open Ria Services Link exists between project &apos;{0}&apos; and project &apos;{1}&apos;..
        /// </summary>
        internal static string RIA_Link_Present {
            get {
                return ResourceManager.GetString("RIA_Link_Present", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shared files will not be copied from &apos;{0}&apos; due to an existing Open Ria Services Link from &apos;{1}&apos;..
        /// </summary>
        internal static string RIA_Link_Prevents_Copy {
            get {
                return ResourceManager.GetString("RIA_Link_Prevents_Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Silverlight project &apos;{0}&apos; has a Open Ria Services Link to the project &apos;{1}&apos; which does not exist.
        ///Did you rename or move that project?
        ///Please modify the Project Properties of &apos;{0}&apos; and set the Open Ria Services Link to point to a valid project..
        /// </summary>
        internal static string Server_Project_File_Does_Not_Exist {
            get {
                return ResourceManager.GetString("Server_Project_File_Does_Not_Exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skipping proxy class generation for &apos;{0}&apos; because a DomainContext for it already exists in another assembly..
        /// </summary>
        internal static string Shared_DomainContext_Skipped {
            get {
                return ResourceManager.GetString("Shared_DomainContext_Skipped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SharedCodeServiceParameters.{0} cannot be null..
        /// </summary>
        internal static string SharedCodeServiceParameters_Parameter_Null {
            get {
                return ResourceManager.GetString("SharedCodeServiceParameters_Parameter_Null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type &apos;{0}&apos; is not derived from Attribute..
        /// </summary>
        internal static string Type_Must_Be_Attribute {
            get {
                return ResourceManager.GetString("Type_Must_Be_Attribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;unspecified&gt;.
        /// </summary>
        internal static string Unspecified_Resource_Element {
            get {
                return ResourceManager.GetString("Unspecified_Resource_Element", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;{0}&apos; custom code generator will be used to generate the proxy classes..
        /// </summary>
        internal static string Using_Custom_Code_Generator {
            get {
                return ResourceManager.GetString("Using_Custom_Code_Generator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;summary&gt;
        ///Context for the RIA application.
        ///&lt;/summary&gt;
        ///&lt;remarks&gt;
        ///This context extends the base to make application services and types available
        ///for consumption from code and xaml.
        ///&lt;/remarks&gt;.
        /// </summary>
        internal static string WebContext_CommentClass {
            get {
                return ResourceManager.GetString("WebContext_CommentClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;summary&gt;
        ///Initializes a new instance of the WebContext class.
        ///&lt;/summary&gt;.
        /// </summary>
        internal static string WebContext_CommentConstructor {
            get {
                return ResourceManager.GetString("WebContext_CommentConstructor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;summary&gt;
        ///Gets the context that is registered as a lifetime object with the current application.
        ///&lt;/summary&gt;
        ///&lt;exception cref=&quot;System.InvalidOperationException&quot;&gt; is thrown if there is no current application,
        ///no contexts have been added, or more than one context has been added.
        ///&lt;/exception&gt;
        ///&lt;seealso cref=&quot;System.Windows.Application.ApplicationLifetimeObjects&quot;/&gt;.
        /// </summary>
        internal static string WebContext_CommentCurrent {
            get {
                return ResourceManager.GetString("WebContext_CommentCurrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;summary&gt;
        ///Gets a user representing the authenticated identity.
        ///&lt;/summary&gt;.
        /// </summary>
        internal static string WebContext_CommentUser {
            get {
                return ResourceManager.GetString("WebContext_CommentUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More than one AuthenticationService exists in the project. No AuthenticationService is set as the default in WebContext.\n{0}.
        /// </summary>
        internal static string WebContext_ManyAuthServices {
            get {
                return ResourceManager.GetString("WebContext_ManyAuthServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Writing generated client proxy classes to &apos;{0}&apos;..
        /// </summary>
        internal static string Writing_Generated_Code {
            get {
                return ResourceManager.GetString("Writing_Generated_Code", resourceCulture);
            }
        }
    }
}
