//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace People
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Linq;
    using System.Runtime.Serialization;
    using System.Threading;
    using System.Threading.Tasks;
    using OpenRiaServices;
    using OpenRiaServices.Client;
    using OpenRiaServices.Client.Authentication;
    
    
    /// <summary>
    /// The 'Lifespan' class.
    /// </summary>
    [DataContract(Namespace="http://schemas.datacontract.org/2004/07/People")]
    public sealed partial class Lifespan : ComplexObject
    {
        
        private DateOnly _born;
        
        private Nullable<DateOnly> _dead;
        
        #region Extensibility Method Definitions

        /// <summary>
        /// This method is invoked from the constructor once initialization is complete and
        /// can be used for further object setup.
        /// </summary>
        partial void OnCreated();
        partial void OnBornChanging(DateOnly value);
        partial void OnBornChanged();
        partial void OnDeadChanging(Nullable<DateOnly> value);
        partial void OnDeadChanged();

        #endregion
        
        
        /// <summary>
        /// Initializes a new instance of the <see cref="Lifespan"/> class.
        /// </summary>
        public Lifespan()
        {
            this.OnCreated();
        }
        
        /// <summary>
        /// Gets or sets the 'Born' value.
        /// </summary>
        [DataMember()]
        public DateOnly Born
        {
            get
            {
                return this._born;
            }
            set
            {
                if ((this._born != value))
                {
                    this.OnBornChanging(value);
                    this.RaiseDataMemberChanging("Born");
                    this.ValidateProperty("Born", value);
                    this._born = value;
                    this.RaiseDataMemberChanged("Born");
                    this.OnBornChanged();
                }
            }
        }
        
        /// <summary>
        /// Gets or sets the 'Dead' value.
        /// </summary>
        [DataMember()]
        public Nullable<DateOnly> Dead
        {
            get
            {
                return this._dead;
            }
            set
            {
                if ((this._dead != value))
                {
                    this.OnDeadChanging(value);
                    this.RaiseDataMemberChanging("Dead");
                    this.ValidateProperty("Dead", value);
                    this._dead = value;
                    this.RaiseDataMemberChanged("Dead");
                    this.OnDeadChanged();
                }
            }
        }
    }
    
    /// <summary>
    /// The 'LunchBreak' class.
    /// </summary>
    [DataContract(Namespace="http://schemas.datacontract.org/2004/07/People")]
    public sealed partial class LunchBreak : ComplexObject
    {
        
        private Nullable<TimeOnly> _endTime;
        
        private TimeOnly _startTime;
        
        #region Extensibility Method Definitions

        /// <summary>
        /// This method is invoked from the constructor once initialization is complete and
        /// can be used for further object setup.
        /// </summary>
        partial void OnCreated();
        partial void OnEndTimeChanging(Nullable<TimeOnly> value);
        partial void OnEndTimeChanged();
        partial void OnStartTimeChanging(TimeOnly value);
        partial void OnStartTimeChanged();

        #endregion
        
        
        /// <summary>
        /// Initializes a new instance of the <see cref="LunchBreak"/> class.
        /// </summary>
        public LunchBreak()
        {
            this.OnCreated();
        }
        
        /// <summary>
        /// Gets or sets the 'EndTime' value.
        /// </summary>
        [DataMember()]
        public Nullable<TimeOnly> EndTime
        {
            get
            {
                return this._endTime;
            }
            set
            {
                if ((this._endTime != value))
                {
                    this.OnEndTimeChanging(value);
                    this.RaiseDataMemberChanging("EndTime");
                    this.ValidateProperty("EndTime", value);
                    this._endTime = value;
                    this.RaiseDataMemberChanged("EndTime");
                    this.OnEndTimeChanged();
                }
            }
        }
        
        /// <summary>
        /// Gets or sets the 'StartTime' value.
        /// </summary>
        [DataMember()]
        public TimeOnly StartTime
        {
            get
            {
                return this._startTime;
            }
            set
            {
                if ((this._startTime != value))
                {
                    this.OnStartTimeChanging(value);
                    this.RaiseDataMemberChanging("StartTime");
                    this.ValidateProperty("StartTime", value);
                    this._startTime = value;
                    this.RaiseDataMemberChanged("StartTime");
                    this.OnStartTimeChanged();
                }
            }
        }
    }
    
    /// <summary>
    /// The DomainContext corresponding to the 'PeopleDomainService' DomainService.
    /// </summary>
    public sealed partial class PeopleDomainContext : DomainContext
    {
        
        #region Extensibility Method Definitions

        /// <summary>
        /// This method is invoked from the constructor once initialization is complete and
        /// can be used for further object setup.
        /// </summary>
        partial void OnCreated();

        #endregion
        
        
        /// <summary>
        /// Initializes a new instance of the <see cref="PeopleDomainContext"/> class.
        /// </summary>
        public PeopleDomainContext() : 
                this(new Uri("People-PeopleDomainService.svc", UriKind.Relative))
        {
        }
        
        /// <summary>
        /// Initializes a new instance of the <see cref="PeopleDomainContext"/> class with the specified service URI.
        /// </summary>
        /// <param name="serviceUri">The PeopleDomainService service URI.</param>
        public PeopleDomainContext(Uri serviceUri) : 
                this(DomainContext.CreateDomainClient(typeof(IPeopleDomainServiceContract), serviceUri, false))
        {
        }
        
        /// <summary>
        /// Initializes a new instance of the <see cref="PeopleDomainContext"/> class with the specified <paramref name="domainClient"/>.
        /// </summary>
        /// <param name="domainClient">The DomainClient instance to use for this DomainContext.</param>
        public PeopleDomainContext(DomainClient domainClient) : 
                base(domainClient)
        {
            this.OnCreated();
        }
        
        /// <summary>
        /// Gets the set of <see cref="Person"/> entity instances that have been loaded into this <see cref="PeopleDomainContext"/> instance.
        /// </summary>
        public EntitySet<Person> Persons
        {
            get
            {
                return base.EntityContainer.GetEntitySet<Person>();
            }
        }
        
        /// <summary>
        /// Gets the set of <see cref="WorkdaySchedule"/> entity instances that have been loaded into this <see cref="PeopleDomainContext"/> instance.
        /// </summary>
        public EntitySet<WorkdaySchedule> WorkdaySchedules
        {
            get
            {
                return base.EntityContainer.GetEntitySet<WorkdaySchedule>();
            }
        }
        
        /// <summary>
        /// Gets an EntityQuery instance that can be used to load <see cref="Person"/> entity instances using the 'GetPersons' query.
        /// </summary>
        /// <returns>An EntityQuery that can be loaded to retrieve <see cref="Person"/> entity instances.</returns>
        public EntityQuery<Person> GetPersonsQuery()
        {
            this.ValidateMethod("GetPersonsQuery", null);
            return base.CreateQuery<Person>("GetPersons", null, false, true);
        }
        
        /// <summary>
        /// Gets an EntityQuery instance that can be used to load <see cref="Person"/> entity instances using the 'GetPersonsByFavouriteDay' query.
        /// </summary>
        /// <param name="favouriteDay">The value for the 'favouriteDay' parameter of the query.</param>
        /// <returns>An EntityQuery that can be loaded to retrieve <see cref="Person"/> entity instances.</returns>
        public EntityQuery<Person> GetPersonsByFavouriteDayQuery(DateOnly favouriteDay)
        {
            Dictionary<string, object> parameters = new Dictionary<string, object>();
            parameters.Add("favouriteDay", favouriteDay);
            this.ValidateMethod("GetPersonsByFavouriteDayQuery", parameters);
            return base.CreateQuery<Person>("GetPersonsByFavouriteDay", parameters, false, true);
        }
        
        /// <summary>
        /// Gets an EntityQuery instance that can be used to load <see cref="Person"/> entity instances using the 'GetPersonsByWeddingDay' query.
        /// </summary>
        /// <param name="weddingDay">The value for the 'weddingDay' parameter of the query.</param>
        /// <returns>An EntityQuery that can be loaded to retrieve <see cref="Person"/> entity instances.</returns>
        public EntityQuery<Person> GetPersonsByWeddingDayQuery(Nullable<DateOnly> weddingDay)
        {
            Dictionary<string, object> parameters = new Dictionary<string, object>();
            parameters.Add("weddingDay", weddingDay);
            this.ValidateMethod("GetPersonsByWeddingDayQuery", parameters);
            return base.CreateQuery<Person>("GetPersonsByWeddingDay", parameters, false, true);
        }
        
        /// <summary>
        /// Gets an EntityQuery instance that can be used to load <see cref="WorkdaySchedule"/> entity instances using the 'GetWorkdayScheduleByEndTime' query.
        /// </summary>
        /// <param name="endTime">The value for the 'endTime' parameter of the query.</param>
        /// <returns>An EntityQuery that can be loaded to retrieve <see cref="WorkdaySchedule"/> entity instances.</returns>
        public EntityQuery<WorkdaySchedule> GetWorkdayScheduleByEndTimeQuery(Nullable<TimeOnly> endTime)
        {
            Dictionary<string, object> parameters = new Dictionary<string, object>();
            parameters.Add("endTime", endTime);
            this.ValidateMethod("GetWorkdayScheduleByEndTimeQuery", parameters);
            return base.CreateQuery<WorkdaySchedule>("GetWorkdayScheduleByEndTime", parameters, false, true);
        }
        
        /// <summary>
        /// Gets an EntityQuery instance that can be used to load <see cref="WorkdaySchedule"/> entity instances using the 'GetWorkdayScheduleByStartTime' query.
        /// </summary>
        /// <param name="startTime">The value for the 'startTime' parameter of the query.</param>
        /// <returns>An EntityQuery that can be loaded to retrieve <see cref="WorkdaySchedule"/> entity instances.</returns>
        public EntityQuery<WorkdaySchedule> GetWorkdayScheduleByStartTimeQuery(TimeOnly startTime)
        {
            Dictionary<string, object> parameters = new Dictionary<string, object>();
            parameters.Add("startTime", startTime);
            this.ValidateMethod("GetWorkdayScheduleByStartTimeQuery", parameters);
            return base.CreateQuery<WorkdaySchedule>("GetWorkdayScheduleByStartTime", parameters, false, true);
        }
        
        /// <summary>
        /// Gets an EntityQuery instance that can be used to load <see cref="WorkdaySchedule"/> entity instances using the 'GetWorkdaySchedules' query.
        /// </summary>
        /// <returns>An EntityQuery that can be loaded to retrieve <see cref="WorkdaySchedule"/> entity instances.</returns>
        public EntityQuery<WorkdaySchedule> GetWorkdaySchedulesQuery()
        {
            this.ValidateMethod("GetWorkdaySchedulesQuery", null);
            return base.CreateQuery<WorkdaySchedule>("GetWorkdaySchedules", null, false, true);
        }
        
        /// <summary>
        /// Asynchronously invokes the 'GetEndTimeById' method of the DomainService.
        /// </summary>
        /// <param name="id">The value for the 'id' parameter of this action.</param>
        /// <param name="callback">Callback to invoke when the operation completes.</param>
        /// <param name="userState">Value to pass to the callback.  It can be <c>null</c>.</param>
        /// <returns>An operation instance that can be used to manage the asynchronous request.</returns>
        public InvokeOperation<Nullable<TimeOnly>> GetEndTimeById(int id, Action<InvokeOperation<Nullable<TimeOnly>>> callback, object userState)
        {
            Dictionary<string, object> parameters = new Dictionary<string, object>();
            parameters.Add("id", id);
            this.ValidateMethod("GetEndTimeById", parameters);
            return this.InvokeOperation<Nullable<TimeOnly>>("GetEndTimeById", typeof(Nullable<TimeOnly>), parameters, true, callback, userState);
        }
        
        /// <summary>
        /// Asynchronously invokes the 'GetEndTimeById' method of the DomainService.
        /// </summary>
        /// <param name="id">The value for the 'id' parameter of this action.</param>
        /// <returns>An operation instance that can be used to manage the asynchronous request.</returns>
        public InvokeOperation<Nullable<TimeOnly>> GetEndTimeById(int id)
        {
            Dictionary<string, object> parameters = new Dictionary<string, object>();
            parameters.Add("id", id);
            this.ValidateMethod("GetEndTimeById", parameters);
            return this.InvokeOperation<Nullable<TimeOnly>>("GetEndTimeById", typeof(Nullable<TimeOnly>), parameters, true, null, null);
        }
        
        /// <summary>
        /// Asynchronously invokes the 'GetEndTimeById' method of the DomainService.
        /// </summary>
        /// <param name="id">The value for the 'id' parameter of this action.</param>
        /// <param name="cancellationToken">A cancellation token that can be used to cancel the work</param>
        /// <returns>An operation instance that can be used to manage the asynchronous request.</returns>
        public System.Threading.Tasks.Task<InvokeResult<Nullable<TimeOnly>>> GetEndTimeByIdAsync(int id, CancellationToken cancellationToken = default(CancellationToken))
        {
            Dictionary<string, object> parameters = new Dictionary<string, object>();
            parameters.Add("id", id);
            this.ValidateMethod("GetEndTimeById", parameters);
            return this.InvokeOperationAsync<Nullable<TimeOnly>>("GetEndTimeById", parameters, true, cancellationToken);
        }
        
        /// <summary>
        /// Asynchronously invokes the 'GetFavouriteDayByName' method of the DomainService.
        /// </summary>
        /// <param name="name">The value for the 'name' parameter of this action.</param>
        /// <param name="callback">Callback to invoke when the operation completes.</param>
        /// <param name="userState">Value to pass to the callback.  It can be <c>null</c>.</param>
        /// <returns>An operation instance that can be used to manage the asynchronous request.</returns>
        public InvokeOperation<DateOnly> GetFavouriteDayByName(string name, Action<InvokeOperation<DateOnly>> callback, object userState)
        {
            Dictionary<string, object> parameters = new Dictionary<string, object>();
            parameters.Add("name", name);
            this.ValidateMethod("GetFavouriteDayByName", parameters);
            return this.InvokeOperation<DateOnly>("GetFavouriteDayByName", typeof(DateOnly), parameters, true, callback, userState);
        }
        
        /// <summary>
        /// Asynchronously invokes the 'GetFavouriteDayByName' method of the DomainService.
        /// </summary>
        /// <param name="name">The value for the 'name' parameter of this action.</param>
        /// <returns>An operation instance that can be used to manage the asynchronous request.</returns>
        public InvokeOperation<DateOnly> GetFavouriteDayByName(string name)
        {
            Dictionary<string, object> parameters = new Dictionary<string, object>();
            parameters.Add("name", name);
            this.ValidateMethod("GetFavouriteDayByName", parameters);
            return this.InvokeOperation<DateOnly>("GetFavouriteDayByName", typeof(DateOnly), parameters, true, null, null);
        }
        
        /// <summary>
        /// Asynchronously invokes the 'GetFavouriteDayByName' method of the DomainService.
        /// </summary>
        /// <param name="name">The value for the 'name' parameter of this action.</param>
        /// <param name="cancellationToken">A cancellation token that can be used to cancel the work</param>
        /// <returns>An operation instance that can be used to manage the asynchronous request.</returns>
        public System.Threading.Tasks.Task<InvokeResult<DateOnly>> GetFavouriteDayByNameAsync(string name, CancellationToken cancellationToken = default(CancellationToken))
        {
            Dictionary<string, object> parameters = new Dictionary<string, object>();
            parameters.Add("name", name);
            this.ValidateMethod("GetFavouriteDayByName", parameters);
            return this.InvokeOperationAsync<DateOnly>("GetFavouriteDayByName", parameters, true, cancellationToken);
        }
        
        /// <summary>
        /// Asynchronously invokes the 'GetLunchBreakById' method of the DomainService.
        /// </summary>
        /// <param name="id">The value for the 'id' parameter of this action.</param>
        /// <param name="callback">Callback to invoke when the operation completes.</param>
        /// <param name="userState">Value to pass to the callback.  It can be <c>null</c>.</param>
        /// <returns>An operation instance that can be used to manage the asynchronous request.</returns>
        public InvokeOperation<LunchBreak> GetLunchBreakById(int id, Action<InvokeOperation<LunchBreak>> callback, object userState)
        {
            Dictionary<string, object> parameters = new Dictionary<string, object>();
            parameters.Add("id", id);
            this.ValidateMethod("GetLunchBreakById", parameters);
            return this.InvokeOperation<LunchBreak>("GetLunchBreakById", typeof(LunchBreak), parameters, true, callback, userState);
        }
        
        /// <summary>
        /// Asynchronously invokes the 'GetLunchBreakById' method of the DomainService.
        /// </summary>
        /// <param name="id">The value for the 'id' parameter of this action.</param>
        /// <returns>An operation instance that can be used to manage the asynchronous request.</returns>
        public InvokeOperation<LunchBreak> GetLunchBreakById(int id)
        {
            Dictionary<string, object> parameters = new Dictionary<string, object>();
            parameters.Add("id", id);
            this.ValidateMethod("GetLunchBreakById", parameters);
            return this.InvokeOperation<LunchBreak>("GetLunchBreakById", typeof(LunchBreak), parameters, true, null, null);
        }
        
        /// <summary>
        /// Asynchronously invokes the 'GetLunchBreakById' method of the DomainService.
        /// </summary>
        /// <param name="id">The value for the 'id' parameter of this action.</param>
        /// <param name="cancellationToken">A cancellation token that can be used to cancel the work</param>
        /// <returns>An operation instance that can be used to manage the asynchronous request.</returns>
        public System.Threading.Tasks.Task<InvokeResult<LunchBreak>> GetLunchBreakByIdAsync(int id, CancellationToken cancellationToken = default(CancellationToken))
        {
            Dictionary<string, object> parameters = new Dictionary<string, object>();
            parameters.Add("id", id);
            this.ValidateMethod("GetLunchBreakById", parameters);
            return this.InvokeOperationAsync<LunchBreak>("GetLunchBreakById", parameters, true, cancellationToken);
        }
        
        /// <summary>
        /// Asynchronously invokes the 'GetPersonLifespanByName' method of the DomainService.
        /// </summary>
        /// <param name="name">The value for the 'name' parameter of this action.</param>
        /// <param name="callback">Callback to invoke when the operation completes.</param>
        /// <param name="userState">Value to pass to the callback.  It can be <c>null</c>.</param>
        /// <returns>An operation instance that can be used to manage the asynchronous request.</returns>
        public InvokeOperation<Lifespan> GetPersonLifespanByName(string name, Action<InvokeOperation<Lifespan>> callback, object userState)
        {
            Dictionary<string, object> parameters = new Dictionary<string, object>();
            parameters.Add("name", name);
            this.ValidateMethod("GetPersonLifespanByName", parameters);
            return this.InvokeOperation<Lifespan>("GetPersonLifespanByName", typeof(Lifespan), parameters, true, callback, userState);
        }
        
        /// <summary>
        /// Asynchronously invokes the 'GetPersonLifespanByName' method of the DomainService.
        /// </summary>
        /// <param name="name">The value for the 'name' parameter of this action.</param>
        /// <returns>An operation instance that can be used to manage the asynchronous request.</returns>
        public InvokeOperation<Lifespan> GetPersonLifespanByName(string name)
        {
            Dictionary<string, object> parameters = new Dictionary<string, object>();
            parameters.Add("name", name);
            this.ValidateMethod("GetPersonLifespanByName", parameters);
            return this.InvokeOperation<Lifespan>("GetPersonLifespanByName", typeof(Lifespan), parameters, true, null, null);
        }
        
        /// <summary>
        /// Asynchronously invokes the 'GetPersonLifespanByName' method of the DomainService.
        /// </summary>
        /// <param name="name">The value for the 'name' parameter of this action.</param>
        /// <param name="cancellationToken">A cancellation token that can be used to cancel the work</param>
        /// <returns>An operation instance that can be used to manage the asynchronous request.</returns>
        public System.Threading.Tasks.Task<InvokeResult<Lifespan>> GetPersonLifespanByNameAsync(string name, CancellationToken cancellationToken = default(CancellationToken))
        {
            Dictionary<string, object> parameters = new Dictionary<string, object>();
            parameters.Add("name", name);
            this.ValidateMethod("GetPersonLifespanByName", parameters);
            return this.InvokeOperationAsync<Lifespan>("GetPersonLifespanByName", parameters, true, cancellationToken);
        }
        
        /// <summary>
        /// Asynchronously invokes the 'GetStartTimeById' method of the DomainService.
        /// </summary>
        /// <param name="id">The value for the 'id' parameter of this action.</param>
        /// <param name="callback">Callback to invoke when the operation completes.</param>
        /// <param name="userState">Value to pass to the callback.  It can be <c>null</c>.</param>
        /// <returns>An operation instance that can be used to manage the asynchronous request.</returns>
        public InvokeOperation<TimeOnly> GetStartTimeById(int id, Action<InvokeOperation<TimeOnly>> callback, object userState)
        {
            Dictionary<string, object> parameters = new Dictionary<string, object>();
            parameters.Add("id", id);
            this.ValidateMethod("GetStartTimeById", parameters);
            return this.InvokeOperation<TimeOnly>("GetStartTimeById", typeof(TimeOnly), parameters, true, callback, userState);
        }
        
        /// <summary>
        /// Asynchronously invokes the 'GetStartTimeById' method of the DomainService.
        /// </summary>
        /// <param name="id">The value for the 'id' parameter of this action.</param>
        /// <returns>An operation instance that can be used to manage the asynchronous request.</returns>
        public InvokeOperation<TimeOnly> GetStartTimeById(int id)
        {
            Dictionary<string, object> parameters = new Dictionary<string, object>();
            parameters.Add("id", id);
            this.ValidateMethod("GetStartTimeById", parameters);
            return this.InvokeOperation<TimeOnly>("GetStartTimeById", typeof(TimeOnly), parameters, true, null, null);
        }
        
        /// <summary>
        /// Asynchronously invokes the 'GetStartTimeById' method of the DomainService.
        /// </summary>
        /// <param name="id">The value for the 'id' parameter of this action.</param>
        /// <param name="cancellationToken">A cancellation token that can be used to cancel the work</param>
        /// <returns>An operation instance that can be used to manage the asynchronous request.</returns>
        public System.Threading.Tasks.Task<InvokeResult<TimeOnly>> GetStartTimeByIdAsync(int id, CancellationToken cancellationToken = default(CancellationToken))
        {
            Dictionary<string, object> parameters = new Dictionary<string, object>();
            parameters.Add("id", id);
            this.ValidateMethod("GetStartTimeById", parameters);
            return this.InvokeOperationAsync<TimeOnly>("GetStartTimeById", parameters, true, cancellationToken);
        }
        
        /// <summary>
        /// Asynchronously invokes the 'GetWeddingDayByName' method of the DomainService.
        /// </summary>
        /// <param name="name">The value for the 'name' parameter of this action.</param>
        /// <param name="callback">Callback to invoke when the operation completes.</param>
        /// <param name="userState">Value to pass to the callback.  It can be <c>null</c>.</param>
        /// <returns>An operation instance that can be used to manage the asynchronous request.</returns>
        public InvokeOperation<Nullable<DateOnly>> GetWeddingDayByName(string name, Action<InvokeOperation<Nullable<DateOnly>>> callback, object userState)
        {
            Dictionary<string, object> parameters = new Dictionary<string, object>();
            parameters.Add("name", name);
            this.ValidateMethod("GetWeddingDayByName", parameters);
            return this.InvokeOperation<Nullable<DateOnly>>("GetWeddingDayByName", typeof(Nullable<DateOnly>), parameters, true, callback, userState);
        }
        
        /// <summary>
        /// Asynchronously invokes the 'GetWeddingDayByName' method of the DomainService.
        /// </summary>
        /// <param name="name">The value for the 'name' parameter of this action.</param>
        /// <returns>An operation instance that can be used to manage the asynchronous request.</returns>
        public InvokeOperation<Nullable<DateOnly>> GetWeddingDayByName(string name)
        {
            Dictionary<string, object> parameters = new Dictionary<string, object>();
            parameters.Add("name", name);
            this.ValidateMethod("GetWeddingDayByName", parameters);
            return this.InvokeOperation<Nullable<DateOnly>>("GetWeddingDayByName", typeof(Nullable<DateOnly>), parameters, true, null, null);
        }
        
        /// <summary>
        /// Asynchronously invokes the 'GetWeddingDayByName' method of the DomainService.
        /// </summary>
        /// <param name="name">The value for the 'name' parameter of this action.</param>
        /// <param name="cancellationToken">A cancellation token that can be used to cancel the work</param>
        /// <returns>An operation instance that can be used to manage the asynchronous request.</returns>
        public System.Threading.Tasks.Task<InvokeResult<Nullable<DateOnly>>> GetWeddingDayByNameAsync(string name, CancellationToken cancellationToken = default(CancellationToken))
        {
            Dictionary<string, object> parameters = new Dictionary<string, object>();
            parameters.Add("name", name);
            this.ValidateMethod("GetWeddingDayByName", parameters);
            return this.InvokeOperationAsync<Nullable<DateOnly>>("GetWeddingDayByName", parameters, true, cancellationToken);
        }
        
        /// <summary>
        /// Creates a new EntityContainer for this DomainContext's EntitySets.
        /// </summary>
        /// <returns>A new container instance.</returns>
        protected override EntityContainer CreateEntityContainer()
        {
            return new PeopleDomainContextEntityContainer();
        }
        
        /// <summary>
        /// Service contract for the 'PeopleDomainService' DomainService.
        /// </summary>
        public interface IPeopleDomainServiceContract
        {
            
            /// <summary>
            /// Asynchronously invokes the 'GetEndTimeById' operation.
            /// </summary>
            /// <param name="id">The value for the 'id' parameter of this action.</param>
            /// <param name="callback">Callback to invoke on completion.</param>
            /// <param name="asyncState">Optional state object.</param>
            /// <returns>An IAsyncResult that can be used to monitor the request.</returns>
            [HasSideEffects(true)]
            IAsyncResult BeginGetEndTimeById(int id, AsyncCallback callback, object asyncState);
            
            /// <summary>
            /// Completes the asynchronous operation begun by 'BeginGetEndTimeById'.
            /// </summary>
            /// <param name="result">The IAsyncResult returned from 'BeginGetEndTimeById'.</param>
            /// <returns>The 'Nullable`1' returned from the 'GetEndTimeById' operation.</returns>
            Nullable<TimeOnly> EndGetEndTimeById(IAsyncResult result);
            
            /// <summary>
            /// Asynchronously invokes the 'GetFavouriteDayByName' operation.
            /// </summary>
            /// <param name="name">The value for the 'name' parameter of this action.</param>
            /// <param name="callback">Callback to invoke on completion.</param>
            /// <param name="asyncState">Optional state object.</param>
            /// <returns>An IAsyncResult that can be used to monitor the request.</returns>
            [HasSideEffects(true)]
            IAsyncResult BeginGetFavouriteDayByName(string name, AsyncCallback callback, object asyncState);
            
            /// <summary>
            /// Completes the asynchronous operation begun by 'BeginGetFavouriteDayByName'.
            /// </summary>
            /// <param name="result">The IAsyncResult returned from 'BeginGetFavouriteDayByName'.</param>
            /// <returns>The 'DateOnly' returned from the 'GetFavouriteDayByName' operation.</returns>
            DateOnly EndGetFavouriteDayByName(IAsyncResult result);
            
            /// <summary>
            /// Asynchronously invokes the 'GetLunchBreakById' operation.
            /// </summary>
            /// <param name="id">The value for the 'id' parameter of this action.</param>
            /// <param name="callback">Callback to invoke on completion.</param>
            /// <param name="asyncState">Optional state object.</param>
            /// <returns>An IAsyncResult that can be used to monitor the request.</returns>
            [HasSideEffects(true)]
            IAsyncResult BeginGetLunchBreakById(int id, AsyncCallback callback, object asyncState);
            
            /// <summary>
            /// Completes the asynchronous operation begun by 'BeginGetLunchBreakById'.
            /// </summary>
            /// <param name="result">The IAsyncResult returned from 'BeginGetLunchBreakById'.</param>
            /// <returns>The 'LunchBreak' returned from the 'GetLunchBreakById' operation.</returns>
            LunchBreak EndGetLunchBreakById(IAsyncResult result);
            
            /// <summary>
            /// Asynchronously invokes the 'GetPersonLifespanByName' operation.
            /// </summary>
            /// <param name="name">The value for the 'name' parameter of this action.</param>
            /// <param name="callback">Callback to invoke on completion.</param>
            /// <param name="asyncState">Optional state object.</param>
            /// <returns>An IAsyncResult that can be used to monitor the request.</returns>
            [HasSideEffects(true)]
            IAsyncResult BeginGetPersonLifespanByName(string name, AsyncCallback callback, object asyncState);
            
            /// <summary>
            /// Completes the asynchronous operation begun by 'BeginGetPersonLifespanByName'.
            /// </summary>
            /// <param name="result">The IAsyncResult returned from 'BeginGetPersonLifespanByName'.</param>
            /// <returns>The 'Lifespan' returned from the 'GetPersonLifespanByName' operation.</returns>
            Lifespan EndGetPersonLifespanByName(IAsyncResult result);
            
            /// <summary>
            /// Asynchronously invokes the 'GetPersons' operation.
            /// </summary>
            /// <param name="callback">Callback to invoke on completion.</param>
            /// <param name="asyncState">Optional state object.</param>
            /// <returns>An IAsyncResult that can be used to monitor the request.</returns>
            [HasSideEffects(false)]
            IAsyncResult BeginGetPersons(AsyncCallback callback, object asyncState);
            
            /// <summary>
            /// Completes the asynchronous operation begun by 'BeginGetPersons'.
            /// </summary>
            /// <param name="result">The IAsyncResult returned from 'BeginGetPersons'.</param>
            /// <returns>The 'QueryResult' returned from the 'GetPersons' operation.</returns>
            QueryResult<Person> EndGetPersons(IAsyncResult result);
            
            /// <summary>
            /// Asynchronously invokes the 'GetPersonsByFavouriteDay' operation.
            /// </summary>
            /// <param name="favouriteDay">The value for the 'favouriteDay' parameter of this action.</param>
            /// <param name="callback">Callback to invoke on completion.</param>
            /// <param name="asyncState">Optional state object.</param>
            /// <returns>An IAsyncResult that can be used to monitor the request.</returns>
            [HasSideEffects(false)]
            IAsyncResult BeginGetPersonsByFavouriteDay(DateOnly favouriteDay, AsyncCallback callback, object asyncState);
            
            /// <summary>
            /// Completes the asynchronous operation begun by 'BeginGetPersonsByFavouriteDay'.
            /// </summary>
            /// <param name="result">The IAsyncResult returned from 'BeginGetPersonsByFavouriteDay'.</param>
            /// <returns>The 'QueryResult' returned from the 'GetPersonsByFavouriteDay' operation.</returns>
            QueryResult<Person> EndGetPersonsByFavouriteDay(IAsyncResult result);
            
            /// <summary>
            /// Asynchronously invokes the 'GetPersonsByWeddingDay' operation.
            /// </summary>
            /// <param name="weddingDay">The value for the 'weddingDay' parameter of this action.</param>
            /// <param name="callback">Callback to invoke on completion.</param>
            /// <param name="asyncState">Optional state object.</param>
            /// <returns>An IAsyncResult that can be used to monitor the request.</returns>
            [HasSideEffects(false)]
            IAsyncResult BeginGetPersonsByWeddingDay(Nullable<DateOnly> weddingDay, AsyncCallback callback, object asyncState);
            
            /// <summary>
            /// Completes the asynchronous operation begun by 'BeginGetPersonsByWeddingDay'.
            /// </summary>
            /// <param name="result">The IAsyncResult returned from 'BeginGetPersonsByWeddingDay'.</param>
            /// <returns>The 'QueryResult' returned from the 'GetPersonsByWeddingDay' operation.</returns>
            QueryResult<Person> EndGetPersonsByWeddingDay(IAsyncResult result);
            
            /// <summary>
            /// Asynchronously invokes the 'GetStartTimeById' operation.
            /// </summary>
            /// <param name="id">The value for the 'id' parameter of this action.</param>
            /// <param name="callback">Callback to invoke on completion.</param>
            /// <param name="asyncState">Optional state object.</param>
            /// <returns>An IAsyncResult that can be used to monitor the request.</returns>
            [HasSideEffects(true)]
            IAsyncResult BeginGetStartTimeById(int id, AsyncCallback callback, object asyncState);
            
            /// <summary>
            /// Completes the asynchronous operation begun by 'BeginGetStartTimeById'.
            /// </summary>
            /// <param name="result">The IAsyncResult returned from 'BeginGetStartTimeById'.</param>
            /// <returns>The 'TimeOnly' returned from the 'GetStartTimeById' operation.</returns>
            TimeOnly EndGetStartTimeById(IAsyncResult result);
            
            /// <summary>
            /// Asynchronously invokes the 'GetWeddingDayByName' operation.
            /// </summary>
            /// <param name="name">The value for the 'name' parameter of this action.</param>
            /// <param name="callback">Callback to invoke on completion.</param>
            /// <param name="asyncState">Optional state object.</param>
            /// <returns>An IAsyncResult that can be used to monitor the request.</returns>
            [HasSideEffects(true)]
            IAsyncResult BeginGetWeddingDayByName(string name, AsyncCallback callback, object asyncState);
            
            /// <summary>
            /// Completes the asynchronous operation begun by 'BeginGetWeddingDayByName'.
            /// </summary>
            /// <param name="result">The IAsyncResult returned from 'BeginGetWeddingDayByName'.</param>
            /// <returns>The 'Nullable`1' returned from the 'GetWeddingDayByName' operation.</returns>
            Nullable<DateOnly> EndGetWeddingDayByName(IAsyncResult result);
            
            /// <summary>
            /// Asynchronously invokes the 'GetWorkdayScheduleByEndTime' operation.
            /// </summary>
            /// <param name="endTime">The value for the 'endTime' parameter of this action.</param>
            /// <param name="callback">Callback to invoke on completion.</param>
            /// <param name="asyncState">Optional state object.</param>
            /// <returns>An IAsyncResult that can be used to monitor the request.</returns>
            [HasSideEffects(false)]
            IAsyncResult BeginGetWorkdayScheduleByEndTime(Nullable<TimeOnly> endTime, AsyncCallback callback, object asyncState);
            
            /// <summary>
            /// Completes the asynchronous operation begun by 'BeginGetWorkdayScheduleByEndTime'.
            /// </summary>
            /// <param name="result">The IAsyncResult returned from 'BeginGetWorkdayScheduleByEndTime'.</param>
            /// <returns>The 'QueryResult' returned from the 'GetWorkdayScheduleByEndTime' operation.</returns>
            QueryResult<WorkdaySchedule> EndGetWorkdayScheduleByEndTime(IAsyncResult result);
            
            /// <summary>
            /// Asynchronously invokes the 'GetWorkdayScheduleByStartTime' operation.
            /// </summary>
            /// <param name="startTime">The value for the 'startTime' parameter of this action.</param>
            /// <param name="callback">Callback to invoke on completion.</param>
            /// <param name="asyncState">Optional state object.</param>
            /// <returns>An IAsyncResult that can be used to monitor the request.</returns>
            [HasSideEffects(false)]
            IAsyncResult BeginGetWorkdayScheduleByStartTime(TimeOnly startTime, AsyncCallback callback, object asyncState);
            
            /// <summary>
            /// Completes the asynchronous operation begun by 'BeginGetWorkdayScheduleByStartTime'.
            /// </summary>
            /// <param name="result">The IAsyncResult returned from 'BeginGetWorkdayScheduleByStartTime'.</param>
            /// <returns>The 'QueryResult' returned from the 'GetWorkdayScheduleByStartTime' operation.</returns>
            QueryResult<WorkdaySchedule> EndGetWorkdayScheduleByStartTime(IAsyncResult result);
            
            /// <summary>
            /// Asynchronously invokes the 'GetWorkdaySchedules' operation.
            /// </summary>
            /// <param name="callback">Callback to invoke on completion.</param>
            /// <param name="asyncState">Optional state object.</param>
            /// <returns>An IAsyncResult that can be used to monitor the request.</returns>
            [HasSideEffects(false)]
            IAsyncResult BeginGetWorkdaySchedules(AsyncCallback callback, object asyncState);
            
            /// <summary>
            /// Completes the asynchronous operation begun by 'BeginGetWorkdaySchedules'.
            /// </summary>
            /// <param name="result">The IAsyncResult returned from 'BeginGetWorkdaySchedules'.</param>
            /// <returns>The 'QueryResult' returned from the 'GetWorkdaySchedules' operation.</returns>
            QueryResult<WorkdaySchedule> EndGetWorkdaySchedules(IAsyncResult result);
        }
        
        internal sealed class PeopleDomainContextEntityContainer : EntityContainer
        {
            
            public PeopleDomainContextEntityContainer()
            {
                this.CreateEntitySet<Person>(EntitySetOperations.None);
                this.CreateEntitySet<WorkdaySchedule>(EntitySetOperations.None);
            }
        }
    }
    
    /// <summary>
    /// The 'Person' entity class.
    /// </summary>
    [DataContract(Namespace="http://schemas.datacontract.org/2004/07/People")]
    public sealed partial class Person : Entity
    {
        
        private DateOnly _favouriteDay;
        
        private Lifespan _lifespan;
        
        private string _name;
        
        private Nullable<DateOnly> _weddingDay;
        
        #region Extensibility Method Definitions

        /// <summary>
        /// This method is invoked from the constructor once initialization is complete and
        /// can be used for further object setup.
        /// </summary>
        partial void OnCreated();
        partial void OnFavouriteDayChanging(DateOnly value);
        partial void OnFavouriteDayChanged();
        partial void OnLifespanChanging(Lifespan value);
        partial void OnLifespanChanged();
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        partial void OnWeddingDayChanging(Nullable<DateOnly> value);
        partial void OnWeddingDayChanged();

        #endregion
        
        
        /// <summary>
        /// Initializes a new instance of the <see cref="Person"/> class.
        /// </summary>
        public Person()
        {
            this.OnCreated();
        }
        
        /// <summary>
        /// Gets or sets the 'FavouriteDay' value.
        /// </summary>
        [DataMember()]
        public DateOnly FavouriteDay
        {
            get
            {
                return this._favouriteDay;
            }
            set
            {
                if ((this._favouriteDay != value))
                {
                    this.OnFavouriteDayChanging(value);
                    this.RaiseDataMemberChanging("FavouriteDay");
                    this.ValidateProperty("FavouriteDay", value);
                    this._favouriteDay = value;
                    this.RaiseDataMemberChanged("FavouriteDay");
                    this.OnFavouriteDayChanged();
                }
            }
        }
        
        /// <summary>
        /// Gets or sets the 'Lifespan' value.
        /// </summary>
        [DataMember()]
        [Display(AutoGenerateField=false)]
        public Lifespan Lifespan
        {
            get
            {
                return this._lifespan;
            }
            set
            {
                if ((this._lifespan != value))
                {
                    this.OnLifespanChanging(value);
                    this.RaiseDataMemberChanging("Lifespan");
                    this.ValidateProperty("Lifespan", value);
                    this._lifespan = value;
                    this.RaiseDataMemberChanged("Lifespan");
                    this.OnLifespanChanged();
                }
            }
        }
        
        /// <summary>
        /// Gets or sets the 'Name' value.
        /// </summary>
        [DataMember()]
        [Editable(false, AllowInitialValue=true)]
        [Key()]
        [RoundtripOriginal()]
        public string Name
        {
            get
            {
                return this._name;
            }
            set
            {
                if ((this._name != value))
                {
                    this.OnNameChanging(value);
                    this.ValidateProperty("Name", value);
                    this._name = value;
                    this.RaisePropertyChanged("Name");
                    this.OnNameChanged();
                }
            }
        }
        
        /// <summary>
        /// Gets or sets the 'WeddingDay' value.
        /// </summary>
        [DataMember()]
        public Nullable<DateOnly> WeddingDay
        {
            get
            {
                return this._weddingDay;
            }
            set
            {
                if ((this._weddingDay != value))
                {
                    this.OnWeddingDayChanging(value);
                    this.RaiseDataMemberChanging("WeddingDay");
                    this.ValidateProperty("WeddingDay", value);
                    this._weddingDay = value;
                    this.RaiseDataMemberChanged("WeddingDay");
                    this.OnWeddingDayChanged();
                }
            }
        }
        
        /// <summary>
        /// Computes a value from the key fields that uniquely identifies this entity instance.
        /// </summary>
        /// <returns>An object instance that uniquely identifies this entity instance.</returns>
        public override object GetIdentity()
        {
            return this._name;
        }
    }
    
    /// <summary>
    /// The 'WorkdaySchedule' entity class.
    /// </summary>
    [DataContract(Namespace="http://schemas.datacontract.org/2004/07/People")]
    public sealed partial class WorkdaySchedule : Entity
    {
        
        private Nullable<TimeOnly> _endTime;
        
        private int _id;
        
        private LunchBreak _lunchBreak;
        
        private TimeOnly _startTime;
        
        #region Extensibility Method Definitions

        /// <summary>
        /// This method is invoked from the constructor once initialization is complete and
        /// can be used for further object setup.
        /// </summary>
        partial void OnCreated();
        partial void OnEndTimeChanging(Nullable<TimeOnly> value);
        partial void OnEndTimeChanged();
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        partial void OnLunchBreakChanging(LunchBreak value);
        partial void OnLunchBreakChanged();
        partial void OnStartTimeChanging(TimeOnly value);
        partial void OnStartTimeChanged();

        #endregion
        
        
        /// <summary>
        /// Initializes a new instance of the <see cref="WorkdaySchedule"/> class.
        /// </summary>
        public WorkdaySchedule()
        {
            this.OnCreated();
        }
        
        /// <summary>
        /// Gets or sets the 'EndTime' value.
        /// </summary>
        [DataMember()]
        public Nullable<TimeOnly> EndTime
        {
            get
            {
                return this._endTime;
            }
            set
            {
                if ((this._endTime != value))
                {
                    this.OnEndTimeChanging(value);
                    this.RaiseDataMemberChanging("EndTime");
                    this.ValidateProperty("EndTime", value);
                    this._endTime = value;
                    this.RaiseDataMemberChanged("EndTime");
                    this.OnEndTimeChanged();
                }
            }
        }
        
        /// <summary>
        /// Gets or sets the 'Id' value.
        /// </summary>
        [DataMember()]
        [Editable(false, AllowInitialValue=true)]
        [Key()]
        [RoundtripOriginal()]
        public int Id
        {
            get
            {
                return this._id;
            }
            set
            {
                if ((this._id != value))
                {
                    this.OnIdChanging(value);
                    this.ValidateProperty("Id", value);
                    this._id = value;
                    this.RaisePropertyChanged("Id");
                    this.OnIdChanged();
                }
            }
        }
        
        /// <summary>
        /// Gets or sets the 'LunchBreak' value.
        /// </summary>
        [DataMember()]
        [Display(AutoGenerateField=false)]
        public LunchBreak LunchBreak
        {
            get
            {
                return this._lunchBreak;
            }
            set
            {
                if ((this._lunchBreak != value))
                {
                    this.OnLunchBreakChanging(value);
                    this.RaiseDataMemberChanging("LunchBreak");
                    this.ValidateProperty("LunchBreak", value);
                    this._lunchBreak = value;
                    this.RaiseDataMemberChanged("LunchBreak");
                    this.OnLunchBreakChanged();
                }
            }
        }
        
        /// <summary>
        /// Gets or sets the 'StartTime' value.
        /// </summary>
        [DataMember()]
        public TimeOnly StartTime
        {
            get
            {
                return this._startTime;
            }
            set
            {
                if ((this._startTime != value))
                {
                    this.OnStartTimeChanging(value);
                    this.RaiseDataMemberChanging("StartTime");
                    this.ValidateProperty("StartTime", value);
                    this._startTime = value;
                    this.RaiseDataMemberChanged("StartTime");
                    this.OnStartTimeChanged();
                }
            }
        }
        
        /// <summary>
        /// Computes a value from the key fields that uniquely identifies this entity instance.
        /// </summary>
        /// <returns>An object instance that uniquely identifies this entity instance.</returns>
        public override object GetIdentity()
        {
            return this._id;
        }
    }
}
