//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace People
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Linq;
    using System.Runtime.Serialization;
    using System.Threading;
    using System.Threading.Tasks;
    using OpenRiaServices;
    using OpenRiaServices.Client;
    using OpenRiaServices.Client.Authentication;
    
    
    /// <summary>
    /// The DomainContext corresponding to the 'PeopleDomainService' DomainService.
    /// </summary>
    public sealed partial class PeopleDomainContext : DomainContext
    {
        
        #region Extensibility Method Definitions

        /// <summary>
        /// This method is invoked from the constructor once initialization is complete and
        /// can be used for further object setup.
        /// </summary>
        partial void OnCreated();

        #endregion
        
        
        /// <summary>
        /// Initializes a new instance of the <see cref="PeopleDomainContext"/> class.
        /// </summary>
        public PeopleDomainContext() : 
                this(new Uri("People-PeopleDomainService.svc", UriKind.Relative))
        {
        }
        
        /// <summary>
        /// Initializes a new instance of the <see cref="PeopleDomainContext"/> class with the specified service URI.
        /// </summary>
        /// <param name="serviceUri">The PeopleDomainService service URI.</param>
        public PeopleDomainContext(Uri serviceUri) : 
                this(DomainContext.CreateDomainClient(typeof(IPeopleDomainServiceContract), serviceUri, false))
        {
        }
        
        /// <summary>
        /// Initializes a new instance of the <see cref="PeopleDomainContext"/> class with the specified <paramref name="domainClient"/>.
        /// </summary>
        /// <param name="domainClient">The DomainClient instance to use for this DomainContext.</param>
        public PeopleDomainContext(DomainClient domainClient) : 
                base(domainClient)
        {
            this.OnCreated();
        }
        
        /// <summary>
        /// Gets the set of <see cref="Person"/> entity instances that have been loaded into this <see cref="PeopleDomainContext"/> instance.
        /// </summary>
        public EntitySet<Person> Persons
        {
            get
            {
                return base.EntityContainer.GetEntitySet<Person>();
            }
        }
        
        /// <summary>
        /// Gets an EntityQuery instance that can be used to load <see cref="Person"/> entity instances using the 'GetPersons' query.
        /// </summary>
        /// <returns>An EntityQuery that can be loaded to retrieve <see cref="Person"/> entity instances.</returns>
        public EntityQuery<Person> GetPersonsQuery()
        {
            this.ValidateMethod("GetPersonsQuery", null);
            return base.CreateQuery<Person>("GetPersons", null, false, true);
        }
        
        /// <summary>
        /// Gets an EntityQuery instance that can be used to load <see cref="Person"/> entity instances using the 'GetPersonsByDate' query.
        /// </summary>
        /// <param name="date">The value for the 'date' parameter of the query.</param>
        /// <returns>An EntityQuery that can be loaded to retrieve <see cref="Person"/> entity instances.</returns>
        public EntityQuery<Person> GetPersonsByDateQuery(DateOnly date)
        {
            Dictionary<string, object> parameters = new Dictionary<string, object>();
            parameters.Add("date", date);
            this.ValidateMethod("GetPersonsByDateQuery", parameters);
            return base.CreateQuery<Person>("GetPersonsByDate", parameters, false, true);
        }
        
        /// <summary>
        /// Asynchronously invokes the 'GetBirthdays' method of the DomainService.
        /// </summary>
        /// <param name="callback">Callback to invoke when the operation completes.</param>
        /// <param name="userState">Value to pass to the callback.  It can be <c>null</c>.</param>
        /// <returns>An operation instance that can be used to manage the asynchronous request.</returns>
        public InvokeOperation<IEnumerable<DateOnly>> GetBirthdays(Action<InvokeOperation<IEnumerable<DateOnly>>> callback, object userState)
        {
            this.ValidateMethod("GetBirthdays", null);
            return this.InvokeOperation<IEnumerable<DateOnly>>("GetBirthdays", typeof(IEnumerable<DateOnly>), null, true, callback, userState);
        }
        
        /// <summary>
        /// Asynchronously invokes the 'GetBirthdays' method of the DomainService.
        /// </summary>
        /// <returns>An operation instance that can be used to manage the asynchronous request.</returns>
        public InvokeOperation<IEnumerable<DateOnly>> GetBirthdays()
        {
            this.ValidateMethod("GetBirthdays", null);
            return this.InvokeOperation<IEnumerable<DateOnly>>("GetBirthdays", typeof(IEnumerable<DateOnly>), null, true, null, null);
        }
        
        /// <summary>
        /// Asynchronously invokes the 'GetBirthdays' method of the DomainService.
        /// </summary>
        /// <param name="cancellationToken">A cancellation token that can be used to cancel the work</param>
        /// <returns>An operation instance that can be used to manage the asynchronous request.</returns>
        public System.Threading.Tasks.Task<InvokeResult<IEnumerable<DateOnly>>> GetBirthdaysAsync(CancellationToken cancellationToken = default(CancellationToken))
        {
            this.ValidateMethod("GetBirthdays", null);
            return this.InvokeOperationAsync<IEnumerable<DateOnly>>("GetBirthdays", null, true, cancellationToken);
        }
        
        /// <summary>
        /// Creates a new EntityContainer for this DomainContext's EntitySets.
        /// </summary>
        /// <returns>A new container instance.</returns>
        protected override EntityContainer CreateEntityContainer()
        {
            return new PeopleDomainContextEntityContainer();
        }
        
        /// <summary>
        /// Service contract for the 'PeopleDomainService' DomainService.
        /// </summary>
        public interface IPeopleDomainServiceContract
        {
            
            /// <summary>
            /// Asynchronously invokes the 'GetBirthdays' operation.
            /// </summary>
            /// <param name="callback">Callback to invoke on completion.</param>
            /// <param name="asyncState">Optional state object.</param>
            /// <returns>An IAsyncResult that can be used to monitor the request.</returns>
            [HasSideEffects(true)]
            IAsyncResult BeginGetBirthdays(AsyncCallback callback, object asyncState);
            
            /// <summary>
            /// Completes the asynchronous operation begun by 'BeginGetBirthdays'.
            /// </summary>
            /// <param name="result">The IAsyncResult returned from 'BeginGetBirthdays'.</param>
            /// <returns>The 'IEnumerable`1' returned from the 'GetBirthdays' operation.</returns>
            IEnumerable<DateOnly> EndGetBirthdays(IAsyncResult result);
            
            /// <summary>
            /// Asynchronously invokes the 'GetPersons' operation.
            /// </summary>
            /// <param name="callback">Callback to invoke on completion.</param>
            /// <param name="asyncState">Optional state object.</param>
            /// <returns>An IAsyncResult that can be used to monitor the request.</returns>
            [HasSideEffects(false)]
            IAsyncResult BeginGetPersons(AsyncCallback callback, object asyncState);
            
            /// <summary>
            /// Completes the asynchronous operation begun by 'BeginGetPersons'.
            /// </summary>
            /// <param name="result">The IAsyncResult returned from 'BeginGetPersons'.</param>
            /// <returns>The 'QueryResult' returned from the 'GetPersons' operation.</returns>
            QueryResult<Person> EndGetPersons(IAsyncResult result);
            
            /// <summary>
            /// Asynchronously invokes the 'GetPersonsByDate' operation.
            /// </summary>
            /// <param name="date">The value for the 'date' parameter of this action.</param>
            /// <param name="callback">Callback to invoke on completion.</param>
            /// <param name="asyncState">Optional state object.</param>
            /// <returns>An IAsyncResult that can be used to monitor the request.</returns>
            [HasSideEffects(false)]
            IAsyncResult BeginGetPersonsByDate(DateOnly date, AsyncCallback callback, object asyncState);
            
            /// <summary>
            /// Completes the asynchronous operation begun by 'BeginGetPersonsByDate'.
            /// </summary>
            /// <param name="result">The IAsyncResult returned from 'BeginGetPersonsByDate'.</param>
            /// <returns>The 'QueryResult' returned from the 'GetPersonsByDate' operation.</returns>
            QueryResult<Person> EndGetPersonsByDate(IAsyncResult result);
        }
        
        internal sealed class PeopleDomainContextEntityContainer : EntityContainer
        {
            
            public PeopleDomainContextEntityContainer()
            {
                this.CreateEntitySet<Person>(EntitySetOperations.None);
            }
        }
    }
    
    /// <summary>
    /// The 'Person' entity class.
    /// </summary>
    [DataContract(Namespace="http://schemas.datacontract.org/2004/07/People")]
    public sealed partial class Person : Entity
    {
        
        private DateOnly _birthday;
        
        private string _name;
        
        #region Extensibility Method Definitions

        /// <summary>
        /// This method is invoked from the constructor once initialization is complete and
        /// can be used for further object setup.
        /// </summary>
        partial void OnCreated();
        partial void OnBirthdayChanging(DateOnly value);
        partial void OnBirthdayChanged();
        partial void OnNameChanging(string value);
        partial void OnNameChanged();

        #endregion
        
        
        /// <summary>
        /// Initializes a new instance of the <see cref="Person"/> class.
        /// </summary>
        public Person()
        {
            this.OnCreated();
        }
        
        /// <summary>
        /// Gets or sets the 'Birthday' value.
        /// </summary>
        [DataMember()]
        public DateOnly Birthday
        {
            get
            {
                return this._birthday;
            }
            set
            {
                if ((this._birthday != value))
                {
                    this.OnBirthdayChanging(value);
                    this.RaiseDataMemberChanging("Birthday");
                    this.ValidateProperty("Birthday", value);
                    this._birthday = value;
                    this.RaiseDataMemberChanged("Birthday");
                    this.OnBirthdayChanged();
                }
            }
        }
        
        /// <summary>
        /// Gets or sets the 'Name' value.
        /// </summary>
        [DataMember()]
        [Editable(false, AllowInitialValue=true)]
        [Key()]
        [RoundtripOriginal()]
        public string Name
        {
            get
            {
                return this._name;
            }
            set
            {
                if ((this._name != value))
                {
                    this.OnNameChanging(value);
                    this.ValidateProperty("Name", value);
                    this._name = value;
                    this.RaisePropertyChanged("Name");
                    this.OnNameChanged();
                }
            }
        }
        
        /// <summary>
        /// Computes a value from the key fields that uniquely identifies this entity instance.
        /// </summary>
        /// <returns>An object instance that uniquely identifies this entity instance.</returns>
        public override object GetIdentity()
        {
            return this._name;
        }
    }
}
