<Project Sdk="MSBuild.SDK.SystemWeb/4.0.107">
  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
    <RootNamespace>TestWap</RootNamespace>
    <AssemblyName>TestWap</AssemblyName>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <MvcBuildViews>false</MvcBuildViews>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="System.Configuration" />
    <Reference Include="System.ComponentModel.DataAnnotations" />
    <Reference Include="System.Drawing" />
    <Reference Include="System.Web" />
    <Reference Include="System.Web.ApplicationServices" />
    <Reference Include="System.Web.DynamicData" />
    <Reference Include="System.Web.Entity" />
    <Reference Include="System.Web.Services" />
    <Reference Include="System.EnterpriseServices" />
    <Reference Include="System.Web.Mobile" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="App_Data\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\OpenRiaServices.Server\Framework\OpenRiaServices.Server.csproj" />
    <ProjectReference Include="..\..\..\OpenRiaServices.Hosting.Wcf\Framework\OpenRiaServices.Hosting.Wcf.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="System.Threading.Tasks.Extensions" Version="4.6.3" />
  </ItemGroup>
</Project>
